// Generated by Framer (beb597f)
import {
    addPropertyControls as e,
    ControlType as l,
    QueryEngine as t
} from "framer";
import {
    DatabaseCollection as a,
    DatabaseDictionaryIndex as r
} from "./aJXMJ7YD_-0.js";
import {
    getRichTextJsonResolver as i
} from "./aJXMJ7YD_-1.js";
let m = {
        A3BoAVNVJ: {
            isNullable: !0,
            type: l.String
        },
        ahLz0bI4v: {
            isNullable: !0,
            type: l.String
        },
        B9ePxUB7k: {
            isNullable: !0,
            type: l.String
        },
        c0PFTDIoS: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        CBW1S5Yms: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        createdAt: {
            isNullable: !0,
            type: l.Date
        },
        d8V0GP6IZ: {
            isNullable: !0,
            type: l.String
        },
        E6VIAved9: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        F3Jqeu5vh: {
            isNullable: !0,
            type: l.String
        },
        fzXRD5z63: {
            isNullable: !0,
            type: l.String
        },
        GnTEcLnoV: {
            isNullable: !0,
            type: l.String
        },
        h88xx3NX_: {
            isNullable: !0,
            type: l.Link
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        iDhNaWYMF: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        IIgGlrBRz: {
            isNullable: !0,
            type: l.String
        },
        kl3xea7TH: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        LeUOkZ0Yz: {
            isNullable: !0,
            type: l.String
        },
        lNML2X8oX: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        mzKqcChtQ: {
            isNullable: !0,
            type: l.String
        },
        NcVQTc0xr: {
            isNullable: !0,
            type: l.String
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        OZUzYuH3J: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        pFi9HNBTM: {
            isNullable: !0,
            type: l.String
        },
        pNAtjtvUV: {
            isNullable: !0,
            type: l.String
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        rbXjqb32P: {
            isNullable: !0,
            type: l.String
        },
        SLXflCgYH: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        suWJKAPaU: {
            isNullable: !0,
            type: l.String
        },
        Td4Xc2DNR: {
            isNullable: !0,
            type: l.String
        },
        TkZ9_uhLT: {
            isNullable: !0,
            type: l.String
        },
        u4qpO7YlX: {
            isNullable: !0,
            type: l.String
        },
        U9PW6V3mh: {
            isNullable: !0,
            type: l.String
        },
        updatedAt: {
            isNullable: !0,
            type: l.Date
        },
        VHG3yRBv8: {
            isNullable: !0,
            type: l.String
        },
        WgBRnS3k0: {
            isNullable: !0,
            type: l.String
        },
        WsrA8ccUJ: {
            isNullable: !0,
            type: l.String
        },
        WxRl76dWD: {
            isNullable: !0,
            type: l.String
        },
        x_AVwdDEb: {
            isNullable: !0,
            type: l.String
        },
        yAcv3h7n1: {
            isNullable: !0,
            type: l.String
        },
        ZI7LUoTGP: {
            isNullable: !0,
            type: l.String
        }
    },
    o = ["id"],
    n = {
        type: 1
    },
    c = ["previousItemId"],
    s = ["nextItemId"],
    u = ["id", "TkZ9_uhLT"],
    f = ["TkZ9_uhLT", "id"],
    d = ["E6VIAved9"],
    p = {
        type: 0
    },
    g = ["ZI7LUoTGP"],
    h = ["GnTEcLnoV"],
    S = ["SLXflCgYH"],
    y = ["kl3xea7TH"],
    N = ["lNML2X8oX"],
    J = ["CBW1S5Yms"],
    w = ["u4qpO7YlX"],
    D = ["NcVQTc0xr"],
    R = ["TkZ9_uhLT"],
    x = ["c0PFTDIoS"],
    L = ["B9ePxUB7k"],
    X = ["Td4Xc2DNR"],
    I = ["ahLz0bI4v"],
    U = ["U9PW6V3mh"],
    T = ["d8V0GP6IZ"],
    Y = ["yAcv3h7n1"],
    b = ["A3BoAVNVJ"],
    V = ["pNAtjtvUV"],
    _ = ["WgBRnS3k0"],
    M = ["h88xx3NX_"],
    v = ["x_AVwdDEb"],
    A = ["F3Jqeu5vh"],
    k = ["IIgGlrBRz"],
    B = ["rbXjqb32P"],
    W = ["mzKqcChtQ"],
    z = ["fzXRD5z63"],
    P = ["iDhNaWYMF"],
    Z = ["LeUOkZ0Yz"],
    C = ["pFi9HNBTM"],
    G = ["suWJKAPaU"],
    H = ["WsrA8ccUJ"],
    q = ["VHG3yRBv8"],
    F = ["WxRl76dWD"],
    O = ["OZUzYuH3J"],
    E = [],
    j = e => {
        let l = E[e];
        if (l) return l().then(e => e.default);
    },
    K = {},
    Q = i(K),
    $ = new t,
    ee = {
        collectionByLocaleId: {
            default: new a({
                chunks: [new URL("./aJXMJ7YD_-chunk-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")],
                id: "b216cafa-2c5f-402b-a69a-8e8a23a1aab2default",
                indexes: [new r({
                    collation: n,
                    collectionSchema: m,
                    fieldNames: o,
                    range: {
                        from: 0,
                        to: 97
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: n,
                    collectionSchema: m,
                    fieldNames: c,
                    range: {
                        from: 97,
                        to: 193
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: n,
                    collectionSchema: m,
                    fieldNames: s,
                    range: {
                        from: 193,
                        to: 285
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: n,
                    collectionSchema: m,
                    fieldNames: u,
                    range: {
                        from: 285,
                        to: 472
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: n,
                    collectionSchema: m,
                    fieldNames: f,
                    range: {
                        from: 472,
                        to: 659
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: d,
                    range: {
                        from: 659,
                        to: 2558
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: g,
                    range: {
                        from: 2558,
                        to: 2671
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: h,
                    range: {
                        from: 2671,
                        to: 2777
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: S,
                    range: {
                        from: 2777,
                        to: 4318
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: y,
                    range: {
                        from: 4318,
                        to: 5847
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: N,
                    range: {
                        from: 5847,
                        to: 7376
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: J,
                    range: {
                        from: 7376,
                        to: 9272
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: w,
                    range: {
                        from: 9272,
                        to: 9411
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: D,
                    range: {
                        from: 9411,
                        to: 9812
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: R,
                    range: {
                        from: 9812,
                        to: 9951
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: x,
                    range: {
                        from: 9951,
                        to: 11841
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: L,
                    range: {
                        from: 11841,
                        to: 11963
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: X,
                    range: {
                        from: 11963,
                        to: 13079
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: I,
                    range: {
                        from: 13079,
                        to: 13753
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: U,
                    range: {
                        from: 13753,
                        to: 13872
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: T,
                    range: {
                        from: 13872,
                        to: 13997
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: Y,
                    range: {
                        from: 13997,
                        to: 14098
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: b,
                    range: {
                        from: 14098,
                        to: 14220
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: V,
                    range: {
                        from: 14220,
                        to: 14333
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: _,
                    range: {
                        from: 14333,
                        to: 14449
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: M,
                    range: {
                        from: 14449,
                        to: 14607
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: v,
                    range: {
                        from: 14607,
                        to: 14744
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: A,
                    range: {
                        from: 14744,
                        to: 15794
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: k,
                    range: {
                        from: 15794,
                        to: 16505
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: B,
                    range: {
                        from: 16505,
                        to: 16597
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: W,
                    range: {
                        from: 16597,
                        to: 16712
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: z,
                    range: {
                        from: 16712,
                        to: 16812
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: P,
                    range: {
                        from: 16812,
                        to: 18717
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: Z,
                    range: {
                        from: 18717,
                        to: 18848
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: C,
                    range: {
                        from: 18848,
                        to: 19815
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: G,
                    range: {
                        from: 19815,
                        to: 20712
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: H,
                    range: {
                        from: 20712,
                        to: 20840
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: q,
                    range: {
                        from: 20840,
                        to: 21831
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: F,
                    range: {
                        from: 21831,
                        to: 22566
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                }), new r({
                    collation: p,
                    collectionSchema: m,
                    fieldNames: O,
                    range: {
                        from: 22566,
                        to: 24494
                    },
                    url: new URL("./aJXMJ7YD_-indexes-default-0.framercms", new URL("../../../../../../../../framerusercontent.com/modules/bDjipPsK2aESq1IJKZdv/dGmTJz9hAKdnaSkNVHUM/aJXMJ7YD_.js", import.meta.url)).href.replace("/modules/", "/cms/")
                })],
                resolveRichText: Q,
                resolveVectorSetItem: j,
                schema: m
            })
        },
        displayName: "Work-Single",
        id: "b216cafa-2c5f-402b-a69a-8e8a23a1aab2"
    };
export default ee;
e(ee, {
    E6VIAved9: {
        title: "Cover Image",
        type: l.ResponsiveImage
    },
    ZI7LUoTGP: {
        defaultValue: "",
        title: "Date",
        type: l.String
    },
    GnTEcLnoV: {
        defaultValue: "",
        title: "Company Name",
        type: l.String
    },
    SLXflCgYH: {
        title: "Slide Show Image 1",
        type: l.ResponsiveImage
    },
    kl3xea7TH: {
        title: "Slide Show Image 2",
        type: l.ResponsiveImage
    },
    lNML2X8oX: {
        title: "Slide Show Image 3",
        type: l.ResponsiveImage
    },
    CBW1S5Yms: {
        title: "BG Image",
        type: l.ResponsiveImage
    },
    u4qpO7YlX: {
        defaultValue: "",
        title: "Title",
        type: l.String
    },
    NcVQTc0xr: {
        defaultValue: "",
        title: "Description",
        type: l.String
    },
    TkZ9_uhLT: {
        preventLocalization: !0,
        title: "Slug",
        type: l.String
    },
    c0PFTDIoS: {
        title: "Image 1",
        type: l.ResponsiveImage
    },
    B9ePxUB7k: {
        defaultValue: "",
        title: "Task Title 1",
        type: l.String
    },
    Td4Xc2DNR: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Description 1",
        type: l.String
    },
    ahLz0bI4v: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Description 2",
        type: l.String
    },
    U9PW6V3mh: {
        defaultValue: "",
        title: "Detail-Title 1",
        type: l.String
    },
    d8V0GP6IZ: {
        defaultValue: "",
        title: "Detail-Subtitle 1",
        type: l.String
    },
    yAcv3h7n1: {
        defaultValue: "",
        title: "Detail-Title 2",
        type: l.String
    },
    A3BoAVNVJ: {
        defaultValue: "",
        title: "Detail-Subtitle 2",
        type: l.String
    },
    pNAtjtvUV: {
        defaultValue: "",
        title: "Detail-Title 3",
        type: l.String
    },
    WgBRnS3k0: {
        defaultValue: "",
        title: "Detail-Subtitle 3",
        type: l.String
    },
    h88xx3NX_: {
        title: "Link Text",
        type: l.Link
    },
    x_AVwdDEb: {
        defaultValue: "",
        title: "Task Title 2",
        type: l.String
    },
    F3Jqeu5vh: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Description 3",
        type: l.String
    },
    IIgGlrBRz: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Description 4",
        type: l.String
    },
    rbXjqb32P: {
        defaultValue: "",
        title: "Tag Title 1",
        type: l.String
    },
    mzKqcChtQ: {
        defaultValue: "",
        title: "Tag Title 2",
        type: l.String
    },
    fzXRD5z63: {
        defaultValue: "",
        title: "Tag Title 3",
        type: l.String
    },
    iDhNaWYMF: {
        title: "Image 2",
        type: l.ResponsiveImage
    },
    LeUOkZ0Yz: {
        defaultValue: "",
        title: "Task Title 3",
        type: l.String
    },
    pFi9HNBTM: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Description 5",
        type: l.String
    },
    suWJKAPaU: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Description 6",
        type: l.String
    },
    WsrA8ccUJ: {
        defaultValue: "",
        title: "Task Title 4",
        type: l.String
    },
    VHG3yRBv8: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Description 7",
        type: l.String
    },
    WxRl76dWD: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Description 8",
        type: l.String
    },
    OZUzYuH3J: {
        title: "Image 3",
        type: l.ResponsiveImage
    },
    createdAt: {
        title: "Created",
        type: l.Date
    },
    updatedAt: {
        title: "Updated",
        type: l.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/aJXMJ7YD_:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/aJXMJ7YD_:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [t] = await $.query({
            from: {
                data: ee,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "TkZ9_uhLT",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l);
        return t ? .TkZ9_uhLT;
    },
    async getRecordIdBySlug(e, l) {
        let [t] = await $.query({
            from: {
                data: ee,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "TkZ9_uhLT",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l);
        return t ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerRecordIdKey": "id",
                "framerData": "true",
                "framerSlug": "TkZ9_uhLT",
                "framerAutoSizeImages": "true",
                "framerEnumToDisplayNameUtils": "2",
                "framerColorSyntax": "false",
                "framerCollectionUtils": "1",
                "framerContractVersion": "1",
                "framerCollectionId": "aJXMJ7YD_"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}