// Generated by Framer (20dc3ed)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    getLoadingLazyAtYPosition,
    Image,
    Link,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "../../../../../../../../framerusercontent.com/modules/mi8d3ECRqhs1I9Z6Yvih/VJSRkJmqKVn25NaCNRar/JgW8Vv0zp.js";
const enabledGestures = {
    pUAcNTqpl: {
        pressed: true
    }
};
const cycleOrder = ["pUAcNTqpl", "C_lfEx9Fm"];
const serializationHash = "framer-XmAX1";
const variantClassNames = {
    C_lfEx9Fm: "framer-v-gnas10",
    pUAcNTqpl: "framer-v-o2pgj8"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 400,
    type: "spring"
};
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Default: "pUAcNTqpl",
    Hover: "C_lfEx9Fm"
};
const getProps = ({
    click,
    height,
    icon,
    id,
    label,
    link,
    width,
    ...props
}) => {
    return { ...props,
        MkhQF2VcI: label ? ? props.MkhQF2VcI ? ? "HOME",
        pXndFB62A: icon ? ? props.pXndFB62A ? ? {
            alt: "",
            pixelHeight: 80,
            pixelWidth: 80,
            src: "../../../../../../../../framerusercontent.com/images/rfAc6IDbX9U3B7fNLCbZELAOiM.png"
        },
        SBbO9G8fG: click ? ? props.SBbO9G8fG,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "pUAcNTqpl",
        Zr7SWn1kA: link ? ? props.Zr7SWn1kA
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        pXndFB62A,
        MkhQF2VcI,
        Zr7SWn1kA,
        SBbO9G8fG,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "pUAcNTqpl",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap1l6y39i = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (SBbO9G8fG) {
            const res = await SBbO9G8fG(...args);
            if (res === false) return false;
        }
    });
    const onMouseEnter1arvbhs = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: true
        });
        setVariant("C_lfEx9Fm");
    });
    const onMouseLeaveqvx0v6 = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: false
        });
        setVariant("pUAcNTqpl");
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: Zr7SWn1kA,
                    motionChild: true,
                    nodeId: "pUAcNTqpl",
                    scopeId: "ieMjNiZph",
                    smoothScroll: true,
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-o2pgj8",className,classNames)} framer-6yc7vq`,
                        "data-framer-name": "Default",
                        "data-highlight": true,
                        layoutDependency: layoutDependency,
                        layoutId: "pUAcNTqpl",
                        onMouseEnter: onMouseEnter1arvbhs,
                        onTap: onTap1l6y39i,
                        ref: refBinding,
                        style: {
                            opacity: .58,
                            ...style
                        },
                        variants: {
                            "pUAcNTqpl-pressed": {
                                opacity: 1
                            },
                            C_lfEx9Fm: {
                                opacity: 1
                            }
                        },
                        ...addPropertyOverrides({
                            "pUAcNTqpl-pressed": {
                                "data-framer-name": undefined
                            },
                            C_lfEx9Fm: {
                                "data-framer-name": "Hover",
                                onMouseEnter: undefined,
                                onMouseLeave: onMouseLeaveqvx0v6
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(Image, {
                            background: {
                                alt: "",
                                fit: "fill",
                                loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (10 + ((componentViewport ? .height || 40) - 20 - 20) / 2)),
                                pixelHeight: 80,
                                pixelWidth: 80,
                                sizes: "20px",
                                ...toResponsiveImage(pXndFB62A)
                            },
                            className: "framer-11pf4cz",
                            "data-framer-name": "Icon",
                            layoutDependency: layoutDependency,
                            layoutId: "TkCY_59QD"
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-qxhczq",
                                    "data-styles-preset": "JgW8Vv0zp",
                                    style: {
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-f9971be2-0af1-45ba-a114-c9040943573d, rgb(238, 238, 238)))"
                                    },
                                    children: "HOME"
                                })
                            }),
                            className: "framer-1skq2qo",
                            "data-framer-name": "HOME",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "kgHWqfHiI",
                            style: {
                                "--extracted-r6o4lv": "var(--token-f9971be2-0af1-45ba-a114-c9040943573d, rgb(238, 238, 238))",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: MkhQF2VcI,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-XmAX1.framer-6yc7vq, .framer-XmAX1 .framer-6yc7vq { display: block; }", ".framer-XmAX1.framer-o2pgj8 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 10px 0px 10px 0px; position: relative; text-decoration: none; width: 244px; }", ".framer-XmAX1 .framer-11pf4cz { aspect-ratio: 1 / 1; flex: none; gap: 0px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 20px; }", ".framer-XmAX1 .framer-1skq2qo { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40
 * @framerIntrinsicWidth 244
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"C_lfEx9Fm":{"layout":["fixed","auto"]},"Xj3eM8lz5":{"layout":["fixed","auto"]}}}
 * @framerVariables {"pXndFB62A":"icon","MkhQF2VcI":"label","Zr7SWn1kA":"link","SBbO9G8fG":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerieMjNiZph = withCSS(Component, css, "framer-XmAX1");
export default FramerieMjNiZph;
FramerieMjNiZph.displayName = "Menu";
FramerieMjNiZph.defaultProps = {
    height: 40,
    width: 244
};
addPropertyControls(FramerieMjNiZph, {
    variant: {
        options: ["pUAcNTqpl", "C_lfEx9Fm"],
        optionTitles: ["Default", "Hover"],
        title: "Variant",
        type: ControlType.Enum
    },
    pXndFB62A: {
        __defaultAssetReference: "data:framer/asset-reference,rfAc6IDbX9U3B7fNLCbZELAOiM.png?originalFilename=home-solid%404x.png&preferredSize=auto",
        __vekterDefault: {
            alt: "",
            assetReference: "data:framer/asset-reference,rfAc6IDbX9U3B7fNLCbZELAOiM.png?originalFilename=home-solid%404x.png&preferredSize=auto"
        },
        title: "Icon",
        type: ControlType.ResponsiveImage
    },
    MkhQF2VcI: {
        defaultValue: "HOME",
        displayTextArea: false,
        title: "Label",
        type: ControlType.String
    },
    Zr7SWn1kA: {
        title: "Link",
        type: ControlType.Link
    },
    SBbO9G8fG: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerieMjNiZph, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "../../../../../../../../framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "../../../../../../../../framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "../../../../../../../../framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "../../../../../../../../framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "../../../../../../../../framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "../../../../../../../../framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "../../../../../../../../framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerieMjNiZph",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "244",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"pXndFB62A\":\"icon\",\"MkhQF2VcI\":\"label\",\"Zr7SWn1kA\":\"link\",\"SBbO9G8fG\":\"click\"}",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"C_lfEx9Fm\":{\"layout\":[\"fixed\",\"auto\"]},\"Xj3eM8lz5\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "40",
                "framerAutoSizeImages": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}