// Generated by Framer (ac3cb42)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addPropertyControls,
    ControlType,
    cx,
    motion,
    withCSS
} from "framer";
import * as React from "react";
import {
    forwardRef
} from "react";
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
    const {
        animated,
        layoutId,
        children,
        ...rest
    } = props;
    return animated ? /*#__PURE__*/ _jsx(motion.div, { ...rest,
        layoutId: layoutId,
        ref: ref
    }) : /*#__PURE__*/ _jsx("div", { ...rest,
        ref: ref
    });
});
const getProps = ({
    fill,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        ezTt3ayMo: fill ? ? props.ezTt3ayMo ? ? "rgb(0, 0, 0)"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        style,
        className,
        layoutId,
        variant,
        ezTt3ayMo,
        ...restProps
    } = getProps(props);
    return /*#__PURE__*/ _jsx(SVG, { ...restProps,
        className: cx("framer-fN7XK", className),
        layoutId: layoutId,
        ref: ref,
        style: {
            "--21h8s6": ezTt3ayMo,
            ...style
        }
    });
});
const css = ['.framer-fN7XK { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url(\'data:image/svg+xml,<svg aria-label="Arrow Up" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 14.781 8.031 C 14.64 8.172 14.449 8.251 14.25 8.251 C 14.051 8.251 13.86 8.172 13.72 8.031 L 8.25 2.561 L 8.25 17.251 C 8.25 17.665 7.915 18.001 7.5 18.001 C 7.086 18.001 6.75 17.665 6.75 17.251 L 6.75 2.561 L 1.281 8.031 C 0.988 8.324 0.513 8.324 0.22 8.031 C -0.073 7.738 -0.073 7.263 0.22 6.97 L 6.97 0.22 C 7.11 0.079 7.301 0 7.5 0 C 7.699 0 7.89 0.079 8.031 0.22 L 14.781 6.97 C 14.922 7.111 15.001 7.302 15.001 7.501 C 15.001 7.7 14.922 7.891 14.781 8.031 Z" fill="var(--21h8s6, rgb(0,0,0))" height="18.00058999231169px" id="kf9hw59lc" opacity="1" transform="translate(4.5 2.999)" width="15.001007063846032px"/></svg>\'); mask-position: center; mask-repeat: no-repeat; width: 24px; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"fill"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Arrow Up","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */
const Icon = withCSS(Component, css, "framer-fN7XK");
export default Icon;
addPropertyControls(Icon, {
    ezTt3ayMo: {
        defaultValue: "rgb(0, 0, 0)",
        hidden: false,
        title: "Fill",
        type: ControlType.Color
    }
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Icon",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "24",
                "framerImmutableVariables": "true",
                "framerVector": "{\"name\":\"Arrow Up\",\"color\":{\"type\":\"variable\",\"value\":\"21h8s6\"},\"set\":{\"localId\":\"vectorSet/NGVKdicsm\",\"id\":\"NGVKdicsm\",\"moduleId\":\"omX0gWFPqDwhaiWwf6ab\"}}",
                "framerSupportedLayoutWidth": "any-prefer-fixed",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "24",
                "framerDisableUnlink": "true",
                "framerVariables": "{\"ezTt3ayMo\":\"fill\"}",
                "framerSupportedLayoutHeight": "any-prefer-fixed"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}