// Generated by Framer (20dc3ed)
import {
    fontStore
} from "framer";
fontStore.loadFonts(["FS;Poppins-regular", "FS;Poppins-bold", "FS;Poppins-bold italic", "FS;Poppins-italic"]);
export const fonts = [{
    explicitInter: true,
    fonts: [{
        family: "Poppins",
        source: "fontshare",
        style: "normal",
        url: "../../../../../../../../framerusercontent.com/third-party-assets/fontshare/wf/NC2MP33RO4WQTSTEEAWBJLAEXNCNEQVF/7F4U3COKLHQH4WUH3AXPC7N4UELEWJQN/JMWNCAGBH3TLANIVQPVABVAVNV5QERTH.woff2",
        weight: "400"
    }, {
        family: "Poppins",
        source: "fontshare",
        style: "normal",
        url: "../../../../../../../../framerusercontent.com/third-party-assets/fontshare/wf/EOHGWBZYYKO6R4PWP4S2B3FFWHHBEZN6/UWQLMF4AFWLXCJQCFV3WRVYC77KZXPRB/FYG6OCH7XOLUUSZTIZE65ATBZWF623O4.woff2",
        weight: "700"
    }, {
        family: "Poppins",
        source: "fontshare",
        style: "italic",
        url: "../../../../../../../../framerusercontent.com/third-party-assets/fontshare/wf/JQL34MORONR7D7BXOVTX3KBGJGEJQ5BJ/CKUZVY5SFANCFAT7FS3MP6ZL4BMEWCJE/NOLRWF3JBJ434MILPG5RB6R2B4HGRSZB.woff2",
        weight: "700"
    }, {
        family: "Poppins",
        source: "fontshare",
        style: "italic",
        url: "../../../../../../../../framerusercontent.com/third-party-assets/fontshare/wf/7LLTLAW3NRWOADG4II2JGKZC6OSEMBQC/EYFXWX77PEMPU645EAWOTG22E375GULW/SSNNTU67MMJH4CSWT443B4KJ7OB4WFHF.woff2",
        weight: "400"
    }]
}];
export const css = ['.framer-QwLqD .framer-styles-preset-uhb4h4:not(.rich-text-wrapper), .framer-QwLqD .framer-styles-preset-uhb4h4.rich-text-wrapper p { --framer-font-family: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-bold-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-family-italic: "Poppins", "Poppins Placeholder", sans-serif; --framer-font-open-type-features: \'blwf\' on, \'cv09\' on, \'cv03\' on, \'cv04\' on, \'cv11\' on; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 28px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-40351340-ff73-4c0e-bc4f-ebeae4bfde51, #111111); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }'];
export const className = "framer-QwLqD";
export const __FramerMetadata__ = {
    "exports": {
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}