// Generated by Framer (eb93fa7)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["k9RwHqedf", "Z0yLtbYlp", "P2Ke3SBs9", "o7bbrmxua", "ioghcaH0A"];
const serializationHash = "framer-rjPUD";
const variantClassNames = {
    ioghcaH0A: "framer-v-s7h0zi",
    k9RwHqedf: "framer-v-1uygu53",
    o7bbrmxua: "framer-v-nlvzf1",
    P2Ke3SBs9: "framer-v-1b1z43q",
    Z0yLtbYlp: "framer-v-1xxim8h"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: .1,
    duration: .3,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Figma: "o7bbrmxua",
    Framer: "k9RwHqedf",
    Premiere: "P2Ke3SBs9",
    PS: "Z0yLtbYlp",
    Webflow: "ioghcaH0A"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "k9RwHqedf"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "k9RwHqedf",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1uygu53", className, classNames),
                    "data-framer-name": "Framer",
                    layoutDependency: layoutDependency,
                    layoutId: "k9RwHqedf",
                    ref: refBinding,
                    style: {
                        backgroundColor: "rgb(42, 42, 42)",
                        borderBottomLeftRadius: 100,
                        borderBottomRightRadius: 100,
                        borderTopLeftRadius: 100,
                        borderTopRightRadius: 100,
                        rotate: -20,
                        ...style
                    },
                    ...addPropertyOverrides({
                        ioghcaH0A: {
                            "data-framer-name": "Webflow"
                        },
                        o7bbrmxua: {
                            "data-framer-name": "Figma"
                        },
                        P2Ke3SBs9: {
                            "data-framer-name": "Premiere"
                        },
                        Z0yLtbYlp: {
                            "data-framer-name": "PS"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(Image, {
                        background: {
                            alt: "skill-image",
                            fit: "fill",
                            loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 101) - 0 - 48) / 2)),
                            pixelHeight: 77,
                            pixelWidth: 77,
                            src: "../../../../../../../../framerusercontent.com/images/5Lx1QgD4ju2ROtmZuLxJ1W6VI.svg"
                        },
                        className: "framer-abh1oc",
                        layoutDependency: layoutDependency,
                        layoutId: "ckS2Flbm1",
                        ...addPropertyOverrides({
                            ioghcaH0A: {
                                background: {
                                    alt: "skill-image",
                                    fit: "fill",
                                    loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 101) - 0 - 48) / 2)),
                                    pixelHeight: 52,
                                    pixelWidth: 48,
                                    src: "../../../../../../../../framerusercontent.com/images/d4Z67mGL5lrcyVQI0RsfW9n7Xe4.svg"
                                }
                            },
                            o7bbrmxua: {
                                background: {
                                    alt: "skill-image",
                                    fit: "fill",
                                    loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 101) - 0 - 48) / 2)),
                                    pixelHeight: 53,
                                    pixelWidth: 46,
                                    src: "../../../../../../../../framerusercontent.com/images/f9H2qtP9iUsqtJd0ok16HG1145E.svg"
                                }
                            },
                            P2Ke3SBs9: {
                                background: {
                                    alt: "skill-image",
                                    fit: "fill",
                                    loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 101) - 0 - 48) / 2)),
                                    pixelHeight: 65,
                                    pixelWidth: 65,
                                    src: "../../../../../../../../framerusercontent.com/images/ZtpO94lbbv22KeJJ4IxbXLLG78c.svg"
                                }
                            },
                            Z0yLtbYlp: {
                                background: {
                                    alt: "skill-image",
                                    fit: "fill",
                                    loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 101) - 0 - 48) / 2)),
                                    pixelHeight: 63,
                                    pixelWidth: 64,
                                    src: "../../../../../../../../framerusercontent.com/images/qBBESK7XrfT1685G8leMuRtAF0.svg"
                                }
                            }
                        }, baseVariant, gestureVariant)
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-rjPUD.framer-fs2bmc, .framer-rjPUD .framer-fs2bmc { display: block; }", ".framer-rjPUD.framer-1uygu53 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 101px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 179px; will-change: var(--framer-will-change-override, transform); }", ".framer-rjPUD .framer-abh1oc { flex: none; height: 48px; position: relative; width: 48px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 101
 * @framerIntrinsicWidth 179
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Z0yLtbYlp":{"layout":["fixed","fixed"]},"P2Ke3SBs9":{"layout":["fixed","fixed"]},"o7bbrmxua":{"layout":["fixed","fixed"]},"ioghcaH0A":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerHtQycQ5rR = withCSS(Component, css, "framer-rjPUD");
export default FramerHtQycQ5rR;
FramerHtQycQ5rR.displayName = "Skills cursor";
FramerHtQycQ5rR.defaultProps = {
    height: 101,
    width: 179
};
addPropertyControls(FramerHtQycQ5rR, {
    variant: {
        options: ["k9RwHqedf", "Z0yLtbYlp", "P2Ke3SBs9", "o7bbrmxua", "ioghcaH0A"],
        optionTitles: ["Framer", "PS", "Premiere", "Figma", "Webflow"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerHtQycQ5rR, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerHtQycQ5rR",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"Z0yLtbYlp\":{\"layout\":[\"fixed\",\"fixed\"]},\"P2Ke3SBs9\":{\"layout\":[\"fixed\",\"fixed\"]},\"o7bbrmxua\":{\"layout\":[\"fixed\",\"fixed\"]},\"ioghcaH0A\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerContractVersion": "1",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "101",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "179"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./HtQycQ5rR.map