// Generated by Framer (f8e3bf6)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    Link,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "../../../../../../../../framerusercontent.com/modules/tNa10spfnGvM7t1v0Xak/JJvNxCjgsWfLSgH4BM6I/nt7A35aXr.js";
const enabledGestures = {
    gRIdsMO31: {
        hover: true
    },
    MjlQLmWkM: {
        hover: true
    }
};
const cycleOrder = ["MjlQLmWkM", "vyJdfXS3Z", "gRIdsMO31"];
const serializationHash = "framer-rCJdB";
const variantClassNames = {
    gRIdsMO31: "framer-v-15scph5",
    MjlQLmWkM: "framer-v-36otxo",
    vyJdfXS3Z: "framer-v-11w784i"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: 0,
    duration: .4,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Wild card": "gRIdsMO31",
    Desktop: "MjlQLmWkM",
    Mobile: "vyJdfXS3Z"
};
const getProps = ({
    click,
    height,
    id,
    link,
    title,
    width,
    ...props
}) => {
    return { ...props,
        BS5SaAWg0: link ? ? props.BS5SaAWg0,
        hK9FfgVOP: click ? ? props.hK9FfgVOP,
        NDS66P9u6: title ? ? props.NDS66P9u6 ? ? "Blog",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "MjlQLmWkM"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        NDS66P9u6,
        BS5SaAWg0,
        hK9FfgVOP,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "MjlQLmWkM",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTapwmr67 = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (hK9FfgVOP) {
            const res = await hK9FfgVOP(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "vyJdfXS3Z") return false;
        return true;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: BS5SaAWg0,
                    motionChild: true,
                    nodeId: "MjlQLmWkM",
                    scopeId: "RuggVfXU4",
                    smoothScroll: true,
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-36otxo",className,classNames)} framer-cpmjn8`,
                        "data-framer-name": "Desktop",
                        "data-highlight": true,
                        layoutDependency: layoutDependency,
                        layoutId: "MjlQLmWkM",
                        onTap: onTapwmr67,
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            "gRIdsMO31-hover": {
                                "data-framer-name": undefined
                            },
                            "MjlQLmWkM-hover": {
                                "data-framer-name": undefined
                            },
                            gRIdsMO31: {
                                "data-framer-name": "Wild card"
                            },
                            vyJdfXS3Z: {
                                "data-framer-name": "Mobile"
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-xclsxu",
                            "data-framer-name": "Title",
                            layoutDependency: layoutDependency,
                            layoutId: "uE8a1A748",
                            children: [ /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-1jywgsz",
                                        "data-styles-preset": "nt7A35aXr",
                                        style: {
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255)))"
                                        },
                                        children: "Blog"
                                    })
                                }),
                                className: "framer-dqwkg6",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "PZw3J67F_",
                                style: {
                                    "--extracted-r6o4lv": "var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255))",
                                    "--framer-paragraph-spacing": "0px"
                                },
                                text: NDS66P9u6,
                                verticalAlignment: "top",
                                withExternalLayout: true
                            }), isDisplayed() && /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-1jywgsz",
                                        "data-styles-preset": "nt7A35aXr",
                                        style: {
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255)))"
                                        },
                                        children: "Blog"
                                    })
                                }),
                                className: "framer-1eqaj9w",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "jHbUNmWDF",
                                style: {
                                    "--extracted-r6o4lv": "var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255))",
                                    "--framer-paragraph-spacing": "0px"
                                },
                                text: NDS66P9u6,
                                verticalAlignment: "top",
                                withExternalLayout: true
                            })]
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-rCJdB.framer-cpmjn8, .framer-rCJdB .framer-cpmjn8 { display: block; }", ".framer-rCJdB.framer-36otxo { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 26px; justify-content: flex-start; overflow: hidden; padding: 2px 20px 0px 0px; position: relative; text-decoration: none; width: min-content; }", ".framer-rCJdB .framer-xclsxu { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 17px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: auto; }", ".framer-rCJdB .framer-dqwkg6, .framer-rCJdB .framer-1eqaj9w { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-rCJdB.framer-v-15scph5 .framer-xclsxu { align-content: center; align-items: center; }", ".framer-rCJdB.framer-v-36otxo.hover.framer-36otxo, .framer-rCJdB.framer-v-15scph5.hover.framer-36otxo { justify-content: flex-end; padding: 0px 20px 3px 0px; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 26
 * @framerIntrinsicWidth 54.7833
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"vyJdfXS3Z":{"layout":["auto","fixed"]},"gRIdsMO31":{"layout":["auto","fixed"]},"qlxhaTYUQ":{"layout":["auto","fixed"]},"GT7_B7KiB":{"layout":["auto","fixed"]}}}
 * @framerVariables {"NDS66P9u6":"title","BS5SaAWg0":"link","hK9FfgVOP":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerRuggVfXU4 = withCSS(Component, css, "framer-rCJdB");
export default FramerRuggVfXU4;
FramerRuggVfXU4.displayName = "Footer Links";
FramerRuggVfXU4.defaultProps = {
    height: 26,
    width: 54.7833
};
addPropertyControls(FramerRuggVfXU4, {
    variant: {
        options: ["MjlQLmWkM", "vyJdfXS3Z", "gRIdsMO31"],
        optionTitles: ["Desktop", "Mobile", "Wild card"],
        title: "Variant",
        type: ControlType.Enum
    },
    NDS66P9u6: {
        defaultValue: "Blog",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    BS5SaAWg0: {
        title: "Link",
        type: ControlType.Link
    },
    hK9FfgVOP: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerRuggVfXU4, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "../../../../../../../../framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "../../../../../../../../framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "../../../../../../../../framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "../../../../../../../../framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "../../../../../../../../framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "../../../../../../../../framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "../../../../../../../../framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerRuggVfXU4",
            "slots": [],
            "annotations": {
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"fixed\"]},\"vyJdfXS3Z\":{\"layout\":[\"auto\",\"fixed\"]},\"gRIdsMO31\":{\"layout\":[\"auto\",\"fixed\"]},\"qlxhaTYUQ\":{\"layout\":[\"auto\",\"fixed\"]},\"GT7_B7KiB\":{\"layout\":[\"auto\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "26",
                "framerVariables": "{\"NDS66P9u6\":\"title\",\"BS5SaAWg0\":\"link\",\"hK9FfgVOP\":\"click\"}",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "54.7833",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./RuggVfXU4.map