// Generated by Framer (55cf326)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    CycleVariantState,
    getFonts,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useOnVariantChange,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import ExperinceCards3 from "../../../../../../../../framerusercontent.com/modules/uWFBvKklLwFnbCzS6RMK/WgeAYVY3fYWrxulZ8Bor/lOrYryn6P.js";
import ExperinceCards1 from "../../../../../../../../framerusercontent.com/modules/rlx0psxRsVKbHNdpePs3/qLu1VtjVbhJIH03A4yP4/qRVw08gPH.js";
import ExperinceCards2 from "../../../../../../../../framerusercontent.com/modules/ub7DtsbONDLZ2hZIjpMs/bV8YnvBpDeFtSRnbaKsT/xibILrwdI.js";
const ExperinceCards1Fonts = getFonts(ExperinceCards1);
const ExperinceCards2Fonts = getFonts(ExperinceCards2);
const ExperinceCards3Fonts = getFonts(ExperinceCards3);
const cycleOrder = ["BSxKOXvyK", "CBHZ_Vfr4", "r86Ta_qoc", "HNtmE8fYP"];
const serializationHash = "framer-06suv";
const variantClassNames = {
    BSxKOXvyK: "framer-v-1q230b",
    CBHZ_Vfr4: "framer-v-m26rx3",
    HNtmE8fYP: "framer-v-1149t05",
    r86Ta_qoc: "framer-v-1e2af8h"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: 0,
    duration: .2,
    ease: [.5, 0, .88, .77],
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Desktop 1": "BSxKOXvyK",
    "Desktop 2": "CBHZ_Vfr4",
    "Desktop 3": "r86Ta_qoc",
    Mobile: "HNtmE8fYP"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "BSxKOXvyK"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "BSxKOXvyK",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onAppearumums8 = activeVariantCallback(async (...args) => {
        await delay(() => setVariant(CycleVariantState, true), 4300);
    });
    const onAppear4cy9pf = activeVariantCallback(async (...args) => {
        await delay(() => setVariant("BSxKOXvyK", true), 4300);
    });
    useOnVariantChange(baseVariant, {
        default: onAppearumums8,
        HNtmE8fYP: undefined,
        r86Ta_qoc: onAppear4cy9pf
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1q230b", className, classNames),
                    "data-framer-name": "Desktop 1",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "BSxKOXvyK",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        CBHZ_Vfr4: {
                            "data-framer-name": "Desktop 2"
                        },
                        HNtmE8fYP: {
                            "data-framer-name": "Mobile",
                            "data-highlight": undefined
                        },
                        r86Ta_qoc: {
                            "data-framer-name": "Desktop 3"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 270,
                        width: `calc(${componentViewport?.width||"100vw"} * 0.4985)`,
                        y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 270) - 0 - 270) / 2),
                        ...addPropertyOverrides({
                            CBHZ_Vfr4: {
                                width: `calc(${componentViewport?.width||"100vw"} * 0.24)`
                            },
                            HNtmE8fYP: {
                                width: componentViewport ? .width || "100vw",
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 928) - 0 - 838) / 2 + 0 + 0)
                            },
                            r86Ta_qoc: {
                                width: `calc(${componentViewport?.width||"100vw"} * 0.24)`
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1lrnyc4-container",
                            layoutDependency: layoutDependency,
                            layoutId: "mGbUnkeTK-container",
                            nodeId: "mGbUnkeTK",
                            rendersWithMotion: true,
                            scopeId: "Eh0p4tdjZ",
                            children: /*#__PURE__*/ _jsx(ExperinceCards1, {
                                b7UA0o1bf: "Senior UI/UX Designer",
                                Crq84k1_f: "Branding",
                                height: "100%",
                                id: "mGbUnkeTK",
                                layoutId: "mGbUnkeTK",
                                style: {
                                    width: "100%"
                                },
                                tX7ja84rO: "UI/UX",
                                variant: "ql6gbgLQ8",
                                width: "100%",
                                Xa6A7svAu: "2023 - Present",
                                ...addPropertyOverrides({
                                    CBHZ_Vfr4: {
                                        variant: "nF35Z4y5c"
                                    },
                                    HNtmE8fYP: {
                                        variant: "tdeBH0Z4A"
                                    },
                                    r86Ta_qoc: {
                                        variant: "nF35Z4y5c"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 270,
                        width: `calc(${componentViewport?.width||"100vw"} * 0.24)`,
                        y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 270) - 0 - 270) / 2),
                        ...addPropertyOverrides({
                            CBHZ_Vfr4: {
                                width: `calc(${componentViewport?.width||"100vw"} / 2)`
                            },
                            HNtmE8fYP: {
                                width: componentViewport ? .width || "100vw",
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 928) - 0 - 838) / 2 + 270 + 14)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-ly759v-container",
                            layoutDependency: layoutDependency,
                            layoutId: "N6hBquvf6-container",
                            nodeId: "N6hBquvf6",
                            rendersWithMotion: true,
                            scopeId: "Eh0p4tdjZ",
                            children: /*#__PURE__*/ _jsx(ExperinceCards2, {
                                b7UA0o1bf: "Art Director",
                                Crq84k1_f: "Performative",
                                height: "100%",
                                id: "N6hBquvf6",
                                layoutId: "N6hBquvf6",
                                style: {
                                    width: "100%"
                                },
                                tX7ja84rO: "Abstract",
                                variant: "JTDNJF2Cx",
                                width: "100%",
                                Xa6A7svAu: "2022 - 2023",
                                ...addPropertyOverrides({
                                    CBHZ_Vfr4: {
                                        variant: "ep8f_EVTt"
                                    },
                                    HNtmE8fYP: {
                                        variant: "jCsajWKBg"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 270,
                        width: `calc(${componentViewport?.width||"100vw"} * 0.24)`,
                        y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 270) - 0 - 270) / 2),
                        ...addPropertyOverrides({
                            HNtmE8fYP: {
                                width: componentViewport ? .width || "100vw",
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 928) - 0 - 838) / 2 + 540 + 28)
                            },
                            r86Ta_qoc: {
                                width: `calc(${componentViewport?.width||"100vw"} / 2)`
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-pbzaiz-container",
                            layoutDependency: layoutDependency,
                            layoutId: "fcll4aVl5-container",
                            nodeId: "fcll4aVl5",
                            rendersWithMotion: true,
                            scopeId: "Eh0p4tdjZ",
                            children: /*#__PURE__*/ _jsx(ExperinceCards3, {
                                b7UA0o1bf: "UI Designer",
                                Crq84k1_f: "Usability Testing",
                                height: "100%",
                                id: "fcll4aVl5",
                                layoutId: "fcll4aVl5",
                                style: {
                                    width: "100%"
                                },
                                tX7ja84rO: "Mobile Design",
                                variant: "ICFXypqXh",
                                width: "100%",
                                Xa6A7svAu: "2020 - 2022",
                                ...addPropertyOverrides({
                                    HNtmE8fYP: {
                                        variant: "iX59mAFzm"
                                    },
                                    r86Ta_qoc: {
                                        variant: "c5HPyZmst"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-06suv.framer-1azaufp, .framer-06suv .framer-1azaufp { display: block; }", ".framer-06suv.framer-1q230b { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1296px; }", ".framer-06suv .framer-1lrnyc4-container { flex: none; height: auto; position: relative; width: 50%; }", ".framer-06suv .framer-ly759v-container, .framer-06suv .framer-pbzaiz-container { flex: none; height: auto; position: relative; width: 24%; }", ".framer-06suv.framer-v-m26rx3 .framer-1lrnyc4-container, .framer-06suv.framer-v-1e2af8h .framer-1lrnyc4-container, .framer-06suv.framer-v-1e2af8h .framer-ly759v-container { width: 24%; }", ".framer-06suv.framer-v-m26rx3 .framer-ly759v-container, .framer-06suv.framer-v-1e2af8h .framer-pbzaiz-container { width: 50%; }", ".framer-06suv.framer-v-1149t05.framer-1q230b { flex-direction: column; width: 671px; }", ".framer-06suv.framer-v-1149t05 .framer-1lrnyc4-container, .framer-06suv.framer-v-1149t05 .framer-ly759v-container, .framer-06suv.framer-v-1149t05 .framer-pbzaiz-container { width: 100%; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 270
 * @framerIntrinsicWidth 1296
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"CBHZ_Vfr4":{"layout":["fixed","auto"]},"r86Ta_qoc":{"layout":["fixed","auto"]},"HNtmE8fYP":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerEh0p4tdjZ = withCSS(Component, css, "framer-06suv");
export default FramerEh0p4tdjZ;
FramerEh0p4tdjZ.displayName = "Experience";
FramerEh0p4tdjZ.defaultProps = {
    height: 270,
    width: 1296
};
addPropertyControls(FramerEh0p4tdjZ, {
    variant: {
        options: ["BSxKOXvyK", "CBHZ_Vfr4", "r86Ta_qoc", "HNtmE8fYP"],
        optionTitles: ["Desktop 1", "Desktop 2", "Desktop 3", "Mobile"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerEh0p4tdjZ, [{
    explicitInter: true,
    fonts: []
}, ...ExperinceCards1Fonts, ...ExperinceCards2Fonts, ...ExperinceCards3Fonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerEh0p4tdjZ",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "270",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"CBHZ_Vfr4\":{\"layout\":[\"fixed\",\"auto\"]},\"r86Ta_qoc\":{\"layout\":[\"fixed\",\"auto\"]},\"HNtmE8fYP\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicWidth": "1296",
                "framerColorSyntax": "true",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}