// Generated by Framer (20dc3ed)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    ComponentViewportProvider,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import FAQAccordion from "../../../../../../../../framerusercontent.com/modules/lUnFvTy7Xr6xNBmTrYWX/0Tg0oHJiWghWQAu3x2Wu/jB2gDnqoz.js";
const FAQAccordionFonts = getFonts(FAQAccordion);
const serializationHash = "framer-H0KVS";
const variantClassNames = {
    CrvMKq9t0: "framer-v-1aowdu3"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "CrvMKq9t0",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1aowdu3", className, classNames),
                    "data-framer-name": "Questions and answers",
                    layoutDependency: layoutDependency,
                    layoutId: "CrvMKq9t0",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 108,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 605) - 0 - 545) / 2 + 0 + 0),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1t7zzq8-container",
                            layoutDependency: layoutDependency,
                            layoutId: "CtD23c0qC-container",
                            nodeId: "CtD23c0qC",
                            rendersWithMotion: true,
                            scopeId: "QpHWAH921",
                            children: /*#__PURE__*/ _jsx(FAQAccordion, {
                                height: "100%",
                                id: "CtD23c0qC",
                                jIYTZ9Ber: "What’s the Portz progress like?",
                                Jk4Ozxuso: "I specialize in UX/UI design, web development, and branding for individuals and businesses.",
                                layoutId: "CtD23c0qC",
                                style: {
                                    width: "100%"
                                },
                                variant: "csoo8gcZr",
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-e609xa",
                        "data-framer-name": "Line",
                        layoutDependency: layoutDependency,
                        layoutId: "AE_zJFWkF",
                        style: {
                            backgroundColor: "var(--token-9bfd3b06-286a-4f02-b84b-6a8de81589fb, rgba(17, 17, 17, 0.1))"
                        }
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 108,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 605) - 0 - 545) / 2 + 109 + 0),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-uhnx8k-container",
                            layoutDependency: layoutDependency,
                            layoutId: "DlM92p4vS-container",
                            nodeId: "DlM92p4vS",
                            rendersWithMotion: true,
                            scopeId: "QpHWAH921",
                            children: /*#__PURE__*/ _jsx(FAQAccordion, {
                                height: "100%",
                                id: "DlM92p4vS",
                                jIYTZ9Ber: "Design delivery time estimate?",
                                Jk4Ozxuso: "As a designer, I offer a range of services including graphic design, web design, branding, illustration.",
                                layoutId: "DlM92p4vS",
                                style: {
                                    width: "100%"
                                },
                                variant: "TRmLY9oqy",
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-3nerqr",
                        "data-framer-name": "Line",
                        layoutDependency: layoutDependency,
                        layoutId: "JlO7gGlEf",
                        style: {
                            backgroundColor: "var(--token-9bfd3b06-286a-4f02-b84b-6a8de81589fb, rgba(17, 17, 17, 0.1))"
                        }
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 108,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 605) - 0 - 545) / 2 + 218 + 0),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1vxy7ko-container",
                            layoutDependency: layoutDependency,
                            layoutId: "HuhRhmjMO-container",
                            nodeId: "HuhRhmjMO",
                            rendersWithMotion: true,
                            scopeId: "QpHWAH921",
                            children: /*#__PURE__*/ _jsx(FAQAccordion, {
                                height: "100%",
                                id: "HuhRhmjMO",
                                jIYTZ9Ber: "What services do you offer?",
                                Jk4Ozxuso: "Absolutely! You can browse through my portfolio on this website to see a selection of my previous projects.",
                                layoutId: "HuhRhmjMO",
                                style: {
                                    width: "100%"
                                },
                                variant: "TRmLY9oqy",
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-106f8im",
                        "data-framer-name": "Line",
                        layoutDependency: layoutDependency,
                        layoutId: "gRPhgCnvM",
                        style: {
                            backgroundColor: "var(--token-9bfd3b06-286a-4f02-b84b-6a8de81589fb, rgba(17, 17, 17, 0.1))"
                        }
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 108,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 605) - 0 - 545) / 2 + 327 + 0),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-11elocj-container",
                            layoutDependency: layoutDependency,
                            layoutId: "psCA98S0V-container",
                            nodeId: "psCA98S0V",
                            rendersWithMotion: true,
                            scopeId: "QpHWAH921",
                            children: /*#__PURE__*/ _jsx(FAQAccordion, {
                                height: "100%",
                                id: "psCA98S0V",
                                jIYTZ9Ber: "What if I don’t like design?",
                                Jk4Ozxuso: "Certainly! My design process typically involves understanding the client's needs and objectives, conducting.",
                                layoutId: "psCA98S0V",
                                style: {
                                    width: "100%"
                                },
                                variant: "TRmLY9oqy",
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-11h736k",
                        "data-framer-name": "Line",
                        layoutDependency: layoutDependency,
                        layoutId: "rwL_M4dwE",
                        style: {
                            backgroundColor: "var(--token-9bfd3b06-286a-4f02-b84b-6a8de81589fb, rgba(17, 17, 17, 0.1))"
                        }
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 108,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 605) - 0 - 545) / 2 + 436 + 0),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-ueql9r-container",
                            layoutDependency: layoutDependency,
                            layoutId: "cETgkP9qI-container",
                            nodeId: "cETgkP9qI",
                            rendersWithMotion: true,
                            scopeId: "QpHWAH921",
                            children: /*#__PURE__*/ _jsx(FAQAccordion, {
                                height: "100%",
                                id: "cETgkP9qI",
                                jIYTZ9Ber: "Are there any refund?",
                                Jk4Ozxuso: "No, you don’t need to know how to code. Our platform offers intuitive tools and templates that allow you to create and manage your website",
                                layoutId: "cETgkP9qI",
                                style: {
                                    width: "100%"
                                },
                                variant: "TRmLY9oqy",
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-44u2mm",
                        "data-framer-name": "Line",
                        layoutDependency: layoutDependency,
                        layoutId: "zrzvrdPt3",
                        style: {
                            backgroundColor: "var(--token-9bfd3b06-286a-4f02-b84b-6a8de81589fb, rgba(17, 17, 17, 0.1))"
                        }
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-H0KVS.framer-2q4ixk, .framer-H0KVS .framer-2q4ixk { display: block; }", ".framer-H0KVS.framer-1aowdu3 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 648px; }", ".framer-H0KVS .framer-1t7zzq8-container, .framer-H0KVS .framer-uhnx8k-container, .framer-H0KVS .framer-1vxy7ko-container, .framer-H0KVS .framer-11elocj-container, .framer-H0KVS .framer-ueql9r-container { flex: none; height: auto; position: relative; width: 100%; z-index: 1; }", ".framer-H0KVS .framer-e609xa, .framer-H0KVS .framer-3nerqr, .framer-H0KVS .framer-106f8im, .framer-H0KVS .framer-11h736k, .framer-H0KVS .framer-44u2mm { flex: none; height: 1px; overflow: hidden; position: relative; width: 100%; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 605
 * @framerIntrinsicWidth 648
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerQpHWAH921 = withCSS(Component, css, "framer-H0KVS");
export default FramerQpHWAH921;
FramerQpHWAH921.displayName = "FAQ section";
FramerQpHWAH921.defaultProps = {
    height: 605,
    width: 648
};
addFonts(FramerQpHWAH921, [{
    explicitInter: true,
    fonts: []
}, ...FAQAccordionFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerQpHWAH921",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "605",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "648",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerComponentViewportWidth": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}