// Generated by Framer (20dc3ed)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    Container,
    ControlType,
    cx,
    GeneratedComponentContext,
    getFonts,
    PropertyOverrides,
    RenderTarget,
    useCustomCursors,
    useHydratedBreakpointVariants,
    useIsOnFramerCanvas,
    useLocaleInfo,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Footer from "#framer/local/canvasComponent/dfZkGvoQ3/dfZkGvoQ3.js";
import Navbar from "#framer/local/canvasComponent/xlkaTNPxS/xlkaTNPxS.js";
const NavbarFonts = getFonts(Navbar);
const FooterFonts = getFonts(Footer);
const breakpoints = {
    hqKfumboX: "(max-width: 809px)",
    qNycwuLgX: "(min-width: 810px) and (max-width: 1439px)",
    VOFxCVVm0: "(min-width: 1440px)"
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-31CyH";
const variantClassNames = {
    hqKfumboX: "framer-v-r8a2ue",
    qNycwuLgX: "framer-v-1nmzu2p",
    VOFxCVVm0: "framer-v-1fo5bxe"
};
const breakpointRules = {
    hqKfumboX: [".framer-31CyH .framer-1lhij4j-container { left: 20px; right: 20px; transform: unset; width: unset; }", ".framer-31CyH .framer-ck014s { flex-direction: column; }", ".framer-31CyH .framer-lay691-container { flex: none; width: 100%; }"],
    qNycwuLgX: [".framer-31CyH .framer-1lhij4j-container { left: 20px; right: 20px; transform: unset; width: unset; }"]
};
const breakpointKeys = Object.keys(breakpointRules);
const selectors = {
    hqKfumboX: ".framer-r8a2ue-override",
    qNycwuLgX: ".framer-1nmzu2p-override"
};
const rules = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-31CyH.framer-1m7mw7x, .framer-31CyH .framer-1m7mw7x { display: block; }", ".framer-31CyH.framer-1fo5bxe { align-content: center; align-items: center; background-color: #000000; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }", ".framer-31CyH .framer-1lhij4j-container { flex: none; height: auto; left: 50%; position: var(--framer-canvas-fixed-position, fixed); top: 0px; transform: translateX(-50%); width: 1296px; z-index: 10; }", ".framer-31CyH .framer-xljpiu { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -0px; position: relative; width: 0px; }", ".framer-31CyH .framer-ck014s { align-content: center; align-items: center; background-color: var(--token-40351340-ff73-4c0e-bc4f-ebeae4bfde51, #111111); display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; order: 1002; overflow: hidden; padding: 0px; position: relative; width: 100%; }", ".framer-31CyH .framer-lay691-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }", '[data-layout-template="true"] > #overlay { margin-bottom: -0px; }'];
const mediaQueries = {
    hqKfumboX: "(max-width: 809px)",
    qNycwuLgX: "(min-width: 810px) and (max-width: 1439px)",
    VOFxCVVm0: "(min-width: 1440px)"
};
const HTMLStyle = ({
    value
}) => {
    const onCanvas = useIsOnFramerCanvas();
    if (onCanvas) return null;
    return /*#__PURE__*/ _jsx("style", {
        dangerouslySetInnerHTML: {
            __html: value
        },
        "data-framer-html-style": ""
    });
};
const humanReadableVariantMap = {
    Desktop: "VOFxCVVm0",
    Phone: "hqKfumboX",
    Tablet: "qNycwuLgX"
};
const getProps = ({
    height,
    id,
    link,
    title,
    width,
    ...props
}) => {
    return { ...props,
        f80Cf9F0p: title ? ? props.f80Cf9F0p ? ? "Back to top",
        mJV797iKJ: link ? ? props.mJV797iKJ,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "VOFxCVVm0"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        mJV797iKJ,
        f80Cf9F0p,
        children,
        ...restProps
    } = getProps(props);
    const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(variant, breakpoints, false);
    const gestureVariant = undefined;
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    useCustomCursors({});
    return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
        value: {
            isLayoutTemplate: true,
            primaryVariantId: "VOFxCVVm0",
            variantClassNames
        },
        children: /*#__PURE__*/ _jsxs(LayoutGroup, {
            id: layoutId ? ? defaultLayoutId,
            children: [ /*#__PURE__*/ _jsx(HTMLStyle, {
                value: ":root body { background: rgb(0, 0, 0); }"
            }), /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                className: cx(scopingClassNames, "framer-1fo5bxe", className),
                "data-layout-template": true,
                ref: refBinding,
                style: { ...style
                },
                children: [ /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                        hqKfumboX: {
                            width: "calc(100vw - 40px)"
                        },
                        qNycwuLgX: {
                            width: "calc(100vw - 40px)"
                        }
                    },
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 94,
                        width: "1296px",
                        y: 0,
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                hqKfumboX: {
                                    "data-framer-layout-hint-center-x": undefined
                                },
                                qNycwuLgX: {
                                    "data-framer-layout-hint-center-x": undefined
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Container, {
                                className: "framer-1lhij4j-container",
                                "data-framer-layout-hint-center-x": true,
                                layoutScroll: true,
                                nodeId: "oebxviDQg",
                                scopeId: "lE7kHDPgD",
                                children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                    breakpoint: baseVariant,
                                    overrides: {
                                        hqKfumboX: {
                                            variant: "RA1K6ici1"
                                        }
                                    },
                                    children: /*#__PURE__*/ _jsx(Navbar, {
                                        height: "100%",
                                        id: "oebxviDQg",
                                        layoutId: "oebxviDQg",
                                        style: {
                                            width: "100%"
                                        },
                                        variant: "zZbf64W_g",
                                        width: "100%"
                                    })
                                })
                            })
                        })
                    })
                }), children, /*#__PURE__*/ _jsx("div", {
                    className: "framer-xljpiu"
                }), /*#__PURE__*/ _jsx("div", {
                    className: "framer-ck014s",
                    "data-framer-name": "Footer section",
                    children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                            hqKfumboX: {
                                width: "100vw"
                            }
                        },
                        children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 984,
                            width: "max(100vw, 1px)",
                            y: 1e3,
                            children: /*#__PURE__*/ _jsx(Container, {
                                className: "framer-lay691-container",
                                nodeId: "X7SDPDRil",
                                scopeId: "lE7kHDPgD",
                                children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                    breakpoint: baseVariant,
                                    overrides: {
                                        hqKfumboX: {
                                            variant: "mLgdonCy6"
                                        },
                                        qNycwuLgX: {
                                            variant: "drRnayTb2"
                                        }
                                    },
                                    children: /*#__PURE__*/ _jsx(Footer, {
                                        height: "100%",
                                        id: "X7SDPDRil",
                                        layoutId: "X7SDPDRil",
                                        MHUE7mlVy: mJV797iKJ,
                                        style: {
                                            width: "100%"
                                        },
                                        variant: "UvfDBfTLl",
                                        width: "100%",
                                        yGIq2y2Dl: f80Cf9F0p
                                    })
                                })
                            })
                        })
                    })
                })]
            }), /*#__PURE__*/ _jsx("div", {
                id: "template-overlay"
            })]
        })
    });
});
const css = target => {
    const isStaticRenderer = target === RenderTarget.canvas || target === RenderTarget.export;
    if (!isStaticRenderer) {
        return [...rules, ...breakpointKeys.map(key => {
            const query = mediaQueries[key];
            return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
        })];
    }
    return [...rules, ...breakpointKeys.flatMap(key => {
        const selector = selectors[key];
        return breakpointRules[key].map(rule => `${selector} {${rule}}`);
    })];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 2000
 * @framerIntrinsicWidth 1440
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"qNycwuLgX":{"layout":["fixed","fixed"]},"hqKfumboX":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"mJV797iKJ":"link","f80Cf9F0p":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"VOFxCVVm0":[".framer-1lhij4j-container",".framer-ck014s"],"qNycwuLgX":[".framer-1lhij4j-container",".framer-ck014s"],"hqKfumboX":[".framer-1lhij4j-container",".framer-ck014s"]}
 * @framerBreakpoints {"VOFxCVVm0":{"min":1440,"canvasClassName":"framer-1fo5bxe-override","minHeight":2000,"name":"Desktop","width":1440,"rootFontSize":16},"qNycwuLgX":{"min":810,"max":1439,"canvasClassName":"framer-1nmzu2p-override","minHeight":2000,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"hqKfumboX":{"max":809,"canvasClassName":"framer-r8a2ue-override","minHeight":2000,"viewportHeight":844,"name":"Phone","width":390,"rootFontSize":16}}
 * @framerDefaultVariant VOFxCVVm0
 * @framerLayoutTemplate
 */
const FramerlE7kHDPgD = withCSS(Component, css, "framer-31CyH");
export default FramerlE7kHDPgD;
FramerlE7kHDPgD.displayName = "Main-Template";
FramerlE7kHDPgD.defaultProps = {
    height: 2e3,
    width: 1440
};
addPropertyControls(FramerlE7kHDPgD, {
    mJV797iKJ: {
        title: "Link",
        type: ControlType.Link
    },
    f80Cf9F0p: {
        defaultValue: "Back to top",
        description: "",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    }
});
addFonts(FramerlE7kHDPgD, [{
    explicitInter: true,
    fonts: []
}, ...NavbarFonts, ...FooterFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerlE7kHDPgD",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"mJV797iKJ\":\"link\",\"f80Cf9F0p\":\"title\"}",
                "framerIntrinsicWidth": "1440",
                "framerDefaultVariant": "VOFxCVVm0",
                "framerHitTargets": "{\"VOFxCVVm0\":[\".framer-1lhij4j-container\",\".framer-ck014s\"],\"qNycwuLgX\":[\".framer-1lhij4j-container\",\".framer-ck014s\"],\"hqKfumboX\":[\".framer-1lhij4j-container\",\".framer-ck014s\"]}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"qNycwuLgX\":{\"layout\":[\"fixed\",\"fixed\"]},\"hqKfumboX\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerBreakpoints": "{\"VOFxCVVm0\":{\"min\":1440,\"canvasClassName\":\"framer-1fo5bxe-override\",\"minHeight\":2000,\"name\":\"Desktop\",\"width\":1440,\"rootFontSize\":16},\"qNycwuLgX\":{\"min\":810,\"max\":1439,\"canvasClassName\":\"framer-1nmzu2p-override\",\"minHeight\":2000,\"viewportHeight\":1080,\"name\":\"Tablet\",\"width\":810,\"rootFontSize\":16},\"hqKfumboX\":{\"max\":809,\"canvasClassName\":\"framer-r8a2ue-override\",\"minHeight\":2000,\"viewportHeight\":844,\"name\":\"Phone\",\"width\":390,\"rootFontSize\":16}}",
                "framerColorSyntax": "true",
                "framerAutoSizeImages": "true",
                "framerLayoutTemplate": "",
                "framerImmutableVariables": "true",
                "framerIntrinsicHeight": "2000"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}