// Generated by Framer (20dc3ed)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getFontsFromSharedStyle,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import {
    Icon as Phosphor
} from "../../../../../../../../framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js";
import * as sharedStyle from "../../../../../../../../framerusercontent.com/modules/tNa10spfnGvM7t1v0Xak/JJvNxCjgsWfLSgH4BM6I/nt7A35aXr.js";
const PhosphorFonts = getFonts(Phosphor);
const cycleOrder = ["m9xHX9YhN", "PKOO7Hltk"];
const serializationHash = "framer-SlYTR";
const variantClassNames = {
    m9xHX9YhN: "framer-v-1s0x8y",
    PKOO7Hltk: "framer-v-1omqzj8"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Primary: "m9xHX9YhN",
    Secondary: "PKOO7Hltk"
};
const getProps = ({
    height,
    id,
    point,
    width,
    ...props
}) => {
    return { ...props,
        sH_PlEGRa: point ? ? props.sH_PlEGRa ? ? "text",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "m9xHX9YhN"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        sH_PlEGRa,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "m9xHX9YhN",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1s0x8y", className, classNames),
                    "data-framer-name": "Primary",
                    layoutDependency: layoutDependency,
                    layoutId: "m9xHX9YhN",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        PKOO7Hltk: {
                            "data-framer-name": "Secondary"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1q1xmg0",
                        "data-framer-name": "Icon",
                        layoutDependency: layoutDependency,
                        layoutId: "oNl0jY3XG",
                        children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1whnuf1-container",
                                isAuthoredByUser: true,
                                isModuleExternal: true,
                                layoutDependency: layoutDependency,
                                layoutId: "GigWo9mFa-container",
                                nodeId: "GigWo9mFa",
                                rendersWithMotion: true,
                                scopeId: "EsvJv5yrl",
                                children: /*#__PURE__*/ _jsx(Phosphor, {
                                    color: "var(--token-43427749-3dbc-4ece-98af-8cf828e7e53e, rgba(17, 17, 17, 0.3))",
                                    height: "100%",
                                    iconSearch: "check",
                                    iconSelection: "House",
                                    id: "GigWo9mFa",
                                    layoutId: "GigWo9mFa",
                                    mirrored: false,
                                    selectByList: false,
                                    style: {
                                        height: "100%",
                                        width: "100%"
                                    },
                                    weight: "bold",
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        PKOO7Hltk: {
                                            color: "var(--token-c9b6bae5-5c18-4565-be79-2b0943175abc, rgba(255, 255, 255, 0.6))"
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-1jywgsz",
                                "data-styles-preset": "nt7A35aXr",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-9d9d73c4-0291-4bff-8e8b-410a7bb6f647, rgba(17, 17, 17, 0.6)))"
                                },
                                children: "text"
                            })
                        }),
                        className: "framer-1vo5r7a",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "I7jV0VvgV",
                        style: {
                            "--extracted-r6o4lv": "var(--token-9d9d73c4-0291-4bff-8e8b-410a7bb6f647, rgba(17, 17, 17, 0.6))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: sH_PlEGRa,
                        variants: {
                            PKOO7Hltk: {
                                "--extracted-r6o4lv": "var(--token-c9b6bae5-5c18-4565-be79-2b0943175abc, rgba(255, 255, 255, 0.6))"
                            }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            PKOO7Hltk: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-1jywgsz",
                                        "data-styles-preset": "nt7A35aXr",
                                        style: {
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c9b6bae5-5c18-4565-be79-2b0943175abc, rgba(255, 255, 255, 0.6)))"
                                        },
                                        children: "text"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-SlYTR.framer-ogctpf, .framer-SlYTR .framer-ogctpf { display: block; }", ".framer-SlYTR.framer-1s0x8y { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 546px; }", ".framer-SlYTR .framer-1q1xmg0 { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 29px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 29px; }", ".framer-SlYTR .framer-1whnuf1-container { flex: none; height: 16px; position: relative; width: 16px; }", ".framer-SlYTR .framer-1vo5r7a { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 29
 * @framerIntrinsicWidth 546
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"PKOO7Hltk":{"layout":["fixed","auto"]}}}
 * @framerVariables {"sH_PlEGRa":"point"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerEsvJv5yrl = withCSS(Component, css, "framer-SlYTR");
export default FramerEsvJv5yrl;
FramerEsvJv5yrl.displayName = "Pricing-Point";
FramerEsvJv5yrl.defaultProps = {
    height: 29,
    width: 546
};
addPropertyControls(FramerEsvJv5yrl, {
    variant: {
        options: ["m9xHX9YhN", "PKOO7Hltk"],
        optionTitles: ["Primary", "Secondary"],
        title: "Variant",
        type: ControlType.Enum
    },
    sH_PlEGRa: {
        defaultValue: "text",
        description: "",
        displayTextArea: false,
        title: "Point",
        type: ControlType.String
    }
});
addFonts(FramerEsvJv5yrl, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "../../../../../../../../framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "../../../../../../../../framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "../../../../../../../../framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "../../../../../../../../framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "../../../../../../../../framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "../../../../../../../../framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "../../../../../../../../framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...PhosphorFonts, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerEsvJv5yrl",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"PKOO7Hltk\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicWidth": "546",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "29",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"sH_PlEGRa\":\"point\"}",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}