// Generated by Framer (9e04080)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    Link,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "../../../../../../../../framerusercontent.com/modules/jvpEOtIODx0cqfc3ubFK/q5bnv3pmJvyO8q6jPC97/IjCKb4exb.js";
import * as sharedStyle1 from "../../../../../../../../framerusercontent.com/modules/rYdHkMOPi6wqIYUY0LN8/JVHZoX6wzibz8q2soNrS/kJt3Jp5S8.js";
const cycleOrder = ["u38ktnfE3", "XZo0Uaz0l", "xxGlwy3Jz", "RlBeYXHNc"];
const serializationHash = "framer-6tnhS";
const variantClassNames = {
    RlBeYXHNc: "framer-v-jxtfoj",
    u38ktnfE3: "framer-v-rlzdm",
    xxGlwy3Jz: "framer-v-yarekq",
    XZo0Uaz0l: "framer-v-yr27gi"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Desktop active": "XZo0Uaz0l",
    "Mobile active": "RlBeYXHNc",
    Desktop: "u38ktnfE3",
    Mobile: "xxGlwy3Jz"
};
const getProps = ({
    awardLink,
    awardName,
    awardTitle,
    date,
    height,
    id,
    newTab,
    width,
    ...props
}) => {
    return { ...props,
        CnzZVvqyN: awardTitle ? ? props.CnzZVvqyN ? ? "SOTY 2023 - 1st Winner",
        FBZa8jNVT: awardLink ? ? props.FBZa8jNVT,
        PjVqGi19I: newTab ? ? props.PjVqGi19I ? ? true,
        tu7HxU6O9: awardName ? ? props.tu7HxU6O9 ? ? "Awwwards",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "u38ktnfE3",
        VjM3_UIPN: date ? ? props.VjM3_UIPN ? ? "May 2023"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        tu7HxU6O9,
        CnzZVvqyN,
        VjM3_UIPN,
        FBZa8jNVT,
        PjVqGi19I,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "u38ktnfE3",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onMouseEnter1j6meti = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: true
        });
        setVariant("XZo0Uaz0l");
    });
    const onMouseLeave1w3cxne = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: false
        });
        setVariant("u38ktnfE3");
    });
    const onMouseEnter11dupb9 = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: true
        });
        setVariant("RlBeYXHNc");
    });
    const onMouseLeave1cbggoi = activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: false
        });
        setVariant("xxGlwy3Jz");
    });
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (["xxGlwy3Jz", "RlBeYXHNc"].includes(baseVariant)) return false;
        return true;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: FBZa8jNVT,
                    motionChild: true,
                    nodeId: "u38ktnfE3",
                    openInNewTab: PjVqGi19I,
                    scopeId: "JUXts0r1f",
                    smoothScroll: true,
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-rlzdm",className,classNames)} framer-308ywt`,
                        "data-border": true,
                        "data-framer-name": "Desktop",
                        "data-highlight": true,
                        layoutDependency: layoutDependency,
                        layoutId: "u38ktnfE3",
                        onMouseEnter: onMouseEnter1j6meti,
                        ref: refBinding,
                        style: {
                            "--border-bottom-width": "0.800000011920929px",
                            "--border-color": "var(--token-9d9d73c4-0291-4bff-8e8b-410a7bb6f647, rgba(17, 17, 17, 0.6))",
                            "--border-left-width": "0px",
                            "--border-right-width": "0px",
                            "--border-style": "solid",
                            "--border-top-width": "0px",
                            ...style
                        },
                        ...addPropertyOverrides({
                            RlBeYXHNc: {
                                "data-framer-name": "Mobile active",
                                onMouseEnter: undefined,
                                onMouseLeave: onMouseLeave1cbggoi
                            },
                            xxGlwy3Jz: {
                                "data-framer-name": "Mobile",
                                onMouseEnter: onMouseEnter11dupb9
                            },
                            XZo0Uaz0l: {
                                "data-framer-name": "Desktop active",
                                onMouseEnter: undefined,
                                onMouseLeave: onMouseLeave1w3cxne
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h5, {
                                    className: "framer-styles-preset-sfbljg",
                                    "data-styles-preset": "IjCKb4exb",
                                    style: {
                                        "--framer-text-color": "var(--extracted-1lwpl3i, var(--token-16dc3c98-97f8-461d-9c35-810928beec08, rgb(189, 189, 189)))"
                                    },
                                    children: "Awwwards"
                                })
                            }),
                            className: "framer-1t2cll4",
                            "data-framer-name": "Awwwards",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "Jjq57fKl3",
                            style: {
                                "--extracted-1lwpl3i": "var(--token-16dc3c98-97f8-461d-9c35-810928beec08, rgb(189, 189, 189))",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: tu7HxU6O9,
                            variants: {
                                XZo0Uaz0l: {
                                    "--extracted-1lwpl3i": "var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255))"
                                }
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                XZo0Uaz0l: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.h5, {
                                            className: "framer-styles-preset-sfbljg",
                                            "data-styles-preset": "IjCKb4exb",
                                            style: {
                                                "--framer-text-color": "var(--extracted-1lwpl3i, var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255)))"
                                            },
                                            children: "Awwwards"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-oedyft",
                                    "data-styles-preset": "kJt3Jp5S8",
                                    style: {
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255)))"
                                    },
                                    children: "SOTY 2023 - 1st Winner"
                                })
                            }),
                            className: "framer-1oq27bd",
                            "data-framer-name": "SOTY 2023 - 1st Winner",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "B0p485X4e",
                            style: {
                                "--extracted-r6o4lv": "var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255))",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: CnzZVvqyN,
                            variants: {
                                RlBeYXHNc: {
                                    "--extracted-r6o4lv": "var(--token-11713805-8bbf-458d-add0-65969babd244, rgb(133, 238, 0))"
                                },
                                XZo0Uaz0l: {
                                    "--extracted-r6o4lv": "var(--token-11713805-8bbf-458d-add0-65969babd244, rgb(133, 238, 0))"
                                }
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                RlBeYXHNc: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            className: "framer-styles-preset-oedyft",
                                            "data-styles-preset": "kJt3Jp5S8",
                                            style: {
                                                "--framer-text-alignment": "right",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-11713805-8bbf-458d-add0-65969babd244, rgb(133, 238, 0)))"
                                            },
                                            children: "SOTY 2023 - 1st Winner"
                                        })
                                    })
                                },
                                xxGlwy3Jz: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            className: "framer-styles-preset-oedyft",
                                            "data-styles-preset": "kJt3Jp5S8",
                                            style: {
                                                "--framer-text-alignment": "right",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255)))"
                                            },
                                            children: "SOTY 2023 - 1st Winner"
                                        })
                                    })
                                },
                                XZo0Uaz0l: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            className: "framer-styles-preset-oedyft",
                                            "data-styles-preset": "kJt3Jp5S8",
                                            style: {
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-11713805-8bbf-458d-add0-65969babd244, rgb(133, 238, 0)))"
                                            },
                                            children: "SOTY 2023 - 1st Winner"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        }), isDisplayed() && /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.h5, {
                                    className: "framer-styles-preset-sfbljg",
                                    "data-styles-preset": "IjCKb4exb",
                                    style: {
                                        "--framer-text-color": "var(--extracted-1lwpl3i, var(--token-16dc3c98-97f8-461d-9c35-810928beec08, rgb(187, 187, 187)))"
                                    },
                                    children: "May 2023"
                                })
                            }),
                            className: "framer-1rfkfgh",
                            "data-framer-name": "May 2023",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "SyKkWaW08",
                            style: {
                                "--extracted-1lwpl3i": "var(--token-16dc3c98-97f8-461d-9c35-810928beec08, rgb(187, 187, 187))",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: VjM3_UIPN,
                            variants: {
                                XZo0Uaz0l: {
                                    "--extracted-1lwpl3i": "var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255))"
                                }
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                XZo0Uaz0l: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.h5, {
                                            className: "framer-styles-preset-sfbljg",
                                            "data-styles-preset": "IjCKb4exb",
                                            style: {
                                                "--framer-text-color": "var(--extracted-1lwpl3i, var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255)))"
                                            },
                                            children: "May 2023"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-6tnhS.framer-308ywt, .framer-6tnhS .framer-308ywt { display: block; }", ".framer-6tnhS.framer-rlzdm { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; height: 65px; justify-content: space-between; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 1102px; }", ".framer-6tnhS .framer-1t2cll4, .framer-6tnhS .framer-1rfkfgh { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-6tnhS .framer-1oq27bd { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", ".framer-6tnhS.framer-v-yarekq.framer-rlzdm, .framer-6tnhS.framer-v-jxtfoj.framer-rlzdm { align-content: flex-start; align-items: flex-start; gap: 60px; height: min-content; justify-content: flex-start; padding: 16px 0px 16px 0px; }", ...sharedStyle.css, ...sharedStyle1.css, '.framer-6tnhS[data-border="true"]::after, .framer-6tnhS [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 65
 * @framerIntrinsicWidth 1102
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"XZo0Uaz0l":{"layout":["fixed","fixed"]},"xxGlwy3Jz":{"layout":["fixed","auto"]},"RlBeYXHNc":{"layout":["fixed","auto"]}}}
 * @framerVariables {"tu7HxU6O9":"awardName","CnzZVvqyN":"awardTitle","VjM3_UIPN":"date","FBZa8jNVT":"awardLink","PjVqGi19I":"newTab"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerJUXts0r1f = withCSS(Component, css, "framer-6tnhS");
export default FramerJUXts0r1f;
FramerJUXts0r1f.displayName = "Award";
FramerJUXts0r1f.defaultProps = {
    height: 65,
    width: 1102
};
addPropertyControls(FramerJUXts0r1f, {
    variant: {
        options: ["u38ktnfE3", "XZo0Uaz0l", "xxGlwy3Jz", "RlBeYXHNc"],
        optionTitles: ["Desktop", "Desktop active", "Mobile", "Mobile active"],
        title: "Variant",
        type: ControlType.Enum
    },
    tu7HxU6O9: {
        defaultValue: "Awwwards",
        displayTextArea: false,
        title: "Award name",
        type: ControlType.String
    },
    CnzZVvqyN: {
        defaultValue: "SOTY 2023 - 1st Winner",
        displayTextArea: false,
        title: "Award title",
        type: ControlType.String
    },
    VjM3_UIPN: {
        defaultValue: "May 2023",
        displayTextArea: false,
        title: "Date",
        type: ControlType.String
    },
    FBZa8jNVT: {
        description: "",
        title: "Award Link",
        type: ControlType.Link
    },
    PjVqGi19I: {
        defaultValue: true,
        title: "New Tab",
        type: ControlType.Boolean
    }
});
addFonts(FramerJUXts0r1f, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "../../../../../../../../framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "../../../../../../../../framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "../../../../../../../../framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "../../../../../../../../framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "../../../../../../../../framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "../../../../../../../../framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "../../../../../../../../framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerJUXts0r1f",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "1102",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"XZo0Uaz0l\":{\"layout\":[\"fixed\",\"fixed\"]},\"xxGlwy3Jz\":{\"layout\":[\"fixed\",\"auto\"]},\"RlBeYXHNc\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicHeight": "65",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerAutoSizeImages": "true",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerVariables": "{\"tu7HxU6O9\":\"awardName\",\"CnzZVvqyN\":\"awardTitle\",\"VjM3_UIPN\":\"date\",\"FBZa8jNVT\":\"awardLink\",\"PjVqGi19I\":\"newTab\"}",
                "framerDisplayContentsDiv": "false"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./JUXts0r1f.map