// Generated by Framer (20dc3ed)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    getLoadingLazyAtYPosition,
    Image,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "../../../../../../../../framerusercontent.com/modules/mJOW1YTyKaR0IcwSzmb3/xPm0QkM58rFc5CvfaLlV/nDa62CoCq.js";
const serializationHash = "framer-pHqNp";
const variantClassNames = {
    LaT9Zf4t1: "framer-v-i0n8q6"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    title,
    width,
    ...props
}) => {
    return { ...props,
        rsMqqIYoS: title ? ? props.rsMqqIYoS ? ? "WEBSITE DESIGN"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        rsMqqIYoS,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "LaT9Zf4t1",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-i0n8q6", className, classNames),
                    "data-framer-name": "Primary",
                    layoutDependency: layoutDependency,
                    layoutId: "LaT9Zf4t1",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h4, {
                                className: "framer-styles-preset-hpcspl",
                                "data-styles-preset": "nDa62CoCq",
                                style: {
                                    "--framer-text-color": "var(--extracted-1eung3n, var(--token-40351340-ff73-4c0e-bc4f-ebeae4bfde51, rgb(17, 17, 17)))"
                                },
                                children: "WEBSITE DESIGN"
                            })
                        }),
                        className: "framer-1sp7l14",
                        "data-framer-name": "WEBSITE DESIGN",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "ijT0u0eZZ",
                        style: {
                            "--extracted-1eung3n": "var(--token-40351340-ff73-4c0e-bc4f-ebeae4bfde51, rgb(17, 17, 17))",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: rsMqqIYoS,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), /*#__PURE__*/ _jsx(Image, {
                        background: {
                            alt: "ticker",
                            fit: "fit",
                            loading: getLoadingLazyAtYPosition((componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 200) - 0 - 40) / 2)),
                            pixelHeight: 40,
                            pixelWidth: 40,
                            positionX: "center",
                            positionY: "center",
                            src: "../../../../../../../../framerusercontent.com/images/6ZNBB53K1h1GjEecIaVB3pbtQc.svg"
                        },
                        className: "framer-1tx1rjb",
                        layoutDependency: layoutDependency,
                        layoutId: "pD6oMqdPC"
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-pHqNp.framer-t2t1s7, .framer-pHqNp .framer-t2t1s7 { display: block; }", ".framer-pHqNp.framer-i0n8q6 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 56px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }", ".framer-pHqNp .framer-1sp7l14 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-pHqNp .framer-1tx1rjb { flex: none; height: 40px; position: relative; width: 40px; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40
 * @framerIntrinsicWidth 325
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"rsMqqIYoS":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerfPm0HPq6L = withCSS(Component, css, "framer-pHqNp");
export default FramerfPm0HPq6L;
FramerfPm0HPq6L.displayName = "Slider-Card";
FramerfPm0HPq6L.defaultProps = {
    height: 40,
    width: 325
};
addPropertyControls(FramerfPm0HPq6L, {
    rsMqqIYoS: {
        defaultValue: "WEBSITE DESIGN",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    }
});
addFonts(FramerfPm0HPq6L, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "../../../../../../../../framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "../../../../../../../../framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "../../../../../../../../framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "../../../../../../../../framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "../../../../../../../../framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "../../../../../../../../framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "../../../../../../../../framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerfPm0HPq6L",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"rsMqqIYoS\":\"title\"}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "325",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicHeight": "40",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}