// Generated by Framer (9e04080)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    SVG,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const cycleOrder = ["rYtxBbviK", "cRBm5cth_"];
const serializationHash = "framer-qSLjq";
const variantClassNames = {
    cRBm5cth_: "framer-v-w9hi3d",
    rYtxBbviK: "framer-v-1ibefur"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Green: "rYtxBbviK",
    White: "cRBm5cth_"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "rYtxBbviK"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "rYtxBbviK",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1ibefur", className, classNames),
                    "data-framer-name": "Green",
                    layoutDependency: layoutDependency,
                    layoutId: "rYtxBbviK",
                    ref: refBinding,
                    style: {
                        borderBottomLeftRadius: "100%",
                        borderBottomRightRadius: "100%",
                        borderTopLeftRadius: "100%",
                        borderTopRightRadius: "100%",
                        ...style
                    },
                    ...addPropertyOverrides({
                        cRBm5cth_: {
                            "data-framer-name": "White"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-me7nu",
                        "data-framer-name": "Icon",
                        layoutDependency: layoutDependency,
                        layoutId: "wbKdWFys8",
                        style: {
                            backdropFilter: "blur(7.559999465942383px)",
                            backgroundColor: "rgba(0, 0, 0, 0.3)",
                            borderBottomLeftRadius: "100%",
                            borderBottomRightRadius: "100%",
                            borderTopLeftRadius: "100%",
                            borderTopRightRadius: "100%",
                            WebkitBackdropFilter: "blur(7.559999465942383px)"
                        },
                        children: /*#__PURE__*/ _jsx(motion.div, {
                            className: "framer-keq7u",
                            "data-framer-name": "Arrow",
                            layoutDependency: layoutDependency,
                            layoutId: "IEZmowMbx",
                            children: /*#__PURE__*/ _jsx(SVG, {
                                className: "framer-pczlpj",
                                "data-framer-name": "Vector",
                                layout: "position",
                                layoutDependency: layoutDependency,
                                layoutId: "EnQ8XpPSd",
                                opacity: 1,
                                svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><path d="M 22.156 1.138 L 22.156 16.871 L 20.414 16.871 L 20.414 4.099 L 2.359 22.154 L 1.139 20.877 L 19.137 2.879 L 6.364 2.879 L 6.364 1.138 Z" fill="var(--token-11713805-8bbf-458d-add0-65969babd244, rgb(133, 238, 0)) /* {&quot;name&quot;:&quot;Primary&quot;} */"></path></svg>',
                                svgContentId: 11522863230,
                                withExternalLayout: true,
                                ...addPropertyOverrides({
                                    cRBm5cth_: {
                                        svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24 24"><path d="M 22.156 1.138 L 22.156 16.871 L 20.414 16.871 L 20.414 4.099 L 2.359 22.154 L 1.139 20.877 L 19.137 2.879 L 6.364 2.879 L 6.364 1.138 Z" fill="var(--token-9ba2e790-1b50-4ca4-8d42-000525b760e1, rgb(255, 255, 255))"></path></svg>',
                                        svgContentId: 9538328221
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-qSLjq.framer-ki7jy7, .framer-qSLjq .framer-ki7jy7 { display: block; }", ".framer-qSLjq.framer-1ibefur { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 57px; justify-content: flex-start; padding: 0px; position: relative; width: 57px; }", ".framer-qSLjq .framer-me7nu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 110px; justify-content: center; padding: 0px; position: relative; width: 110px; }", ".framer-qSLjq .framer-keq7u { flex: none; gap: 0px; height: 28px; overflow: hidden; position: relative; width: 28px; }", ".framer-qSLjq .framer-pczlpj { flex: none; height: 24px; left: 2px; position: absolute; top: 2px; width: 24px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 57
 * @framerIntrinsicWidth 57
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"cRBm5cth_":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerzUElnC4p0 = withCSS(Component, css, "framer-qSLjq");
export default FramerzUElnC4p0;
FramerzUElnC4p0.displayName = "Custom-Cursor";
FramerzUElnC4p0.defaultProps = {
    height: 57,
    width: 57
};
addPropertyControls(FramerzUElnC4p0, {
    variant: {
        options: ["rYtxBbviK", "cRBm5cth_"],
        optionTitles: ["Green", "White"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerzUElnC4p0, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerzUElnC4p0",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "57",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"cRBm5cth_\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "57",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerAutoSizeImages": "true",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./zUElnC4p0.map