// Generated by Framer (20dc3ed)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    SVG,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "../../../../../../../../framerusercontent.com/modules/rYdHkMOPi6wqIYUY0LN8/JVHZoX6wzibz8q2soNrS/kJt3Jp5S8.js";
const cycleOrder = ["TRmLY9oqy", "csoo8gcZr"];
const serializationHash = "framer-b855M";
const variantClassNames = {
    csoo8gcZr: "framer-v-b8oll3",
    TRmLY9oqy: "framer-v-wxbu4l"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Close: "TRmLY9oqy",
    Open: "csoo8gcZr"
};
const getProps = ({
    answer,
    height,
    id,
    question,
    width,
    ...props
}) => {
    return { ...props,
        jIYTZ9Ber: question ? ? props.jIYTZ9Ber ? ? "What’s the Portz progress like?",
        Jk4Ozxuso: answer ? ? props.Jk4Ozxuso ? ? "I specialize in UX/UI design, web development, and branding for individuals and businesses.",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "TRmLY9oqy"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        jIYTZ9Ber,
        Jk4Ozxuso,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "TRmLY9oqy",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap1pazzk4 = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        setVariant("csoo8gcZr");
    });
    const onTap1kk8rex = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        setVariant("TRmLY9oqy");
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "csoo8gcZr") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-wxbu4l", className, classNames),
                    "data-framer-name": "Close",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "TRmLY9oqy",
                    onTap: onTap1pazzk4,
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-f9971be2-0af1-45ba-a114-c9040943573d, rgb(238, 238, 238))",
                        ...style
                    },
                    ...addPropertyOverrides({
                        csoo8gcZr: {
                            "data-framer-name": "Open",
                            onTap: onTap1kk8rex
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1tmyzos",
                        "data-framer-name": "Content",
                        layoutDependency: layoutDependency,
                        layoutId: "bQOw_z2Dg",
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-oedyft",
                                    "data-styles-preset": "kJt3Jp5S8",
                                    style: {
                                        "--framer-text-alignment": "left",
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-40351340-ff73-4c0e-bc4f-ebeae4bfde51, rgb(17, 17, 17)))"
                                    },
                                    children: "What’s the Portz progress like?"
                                })
                            }),
                            className: "framer-a032bh",
                            "data-framer-name": "Question",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "kenF3a2Nu",
                            style: {
                                "--extracted-r6o4lv": "var(--token-40351340-ff73-4c0e-bc4f-ebeae4bfde51, rgb(17, 17, 17))",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: jIYTZ9Ber,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        }), isDisplayed() && /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-oedyft",
                                    "data-styles-preset": "kJt3Jp5S8",
                                    style: {
                                        "--framer-text-alignment": "left",
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-9d9d73c4-0291-4bff-8e8b-410a7bb6f647, rgba(17, 17, 17, 0.6)))"
                                    },
                                    children: "I specialize in UX/UI design, web development, and branding for individuals and businesses."
                                })
                            }),
                            className: "framer-1pxx5uj",
                            "data-framer-name": "Answer",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "o70BS6GDD",
                            style: {
                                "--extracted-r6o4lv": "var(--token-9d9d73c4-0291-4bff-8e8b-410a7bb6f647, rgba(17, 17, 17, 0.6))",
                                "--framer-paragraph-spacing": "0px"
                            },
                            text: Jk4Ozxuso,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    }), /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1o4y26t",
                        "data-border": true,
                        "data-framer-name": "Button Icon",
                        layoutDependency: layoutDependency,
                        layoutId: "KTZ6ReGpF",
                        style: {
                            "--border-bottom-width": "1px",
                            "--border-color": "var(--token-1125e959-6900-4d29-9ace-de10cfd0401a, rgba(17, 17, 17, 0.2))",
                            "--border-left-width": "1px",
                            "--border-right-width": "1px",
                            "--border-style": "solid",
                            "--border-top-width": "1px",
                            borderBottomLeftRadius: 32,
                            borderBottomRightRadius: 32,
                            borderTopLeftRadius: 32,
                            borderTopRightRadius: 32,
                            rotate: 0
                        },
                        variants: {
                            csoo8gcZr: {
                                "--border-color": "var(--token-9bfd3b06-286a-4f02-b84b-6a8de81589fb, rgba(17, 17, 17, 0.2))",
                                rotate: -45
                            }
                        },
                        children: /*#__PURE__*/ _jsx(SVG, {
                            className: "framer-qz0us0",
                            "data-framer-name": "Vector",
                            layout: "position",
                            layoutDependency: layoutDependency,
                            layoutId: "P7ADfqe5B",
                            opacity: 1,
                            svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 15 15"><path d="M 6.855 0.827 L 6.855 6.893 L 0.41 6.893 L 0.41 8.107 L 6.855 8.107 L 6.855 14.173 L 8.145 14.173 L 8.145 8.107 L 14.59 8.107 L 14.59 6.893 L 8.145 6.893 L 8.145 0.827 Z" fill="var(--token-40351340-ff73-4c0e-bc4f-ebeae4bfde51, rgb(17, 17, 17))"></path></svg>',
                            svgContentId: 11164967158,
                            withExternalLayout: true
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-b855M.framer-19hx24r, .framer-b855M .framer-19hx24r { display: block; }", ".framer-b855M.framer-wxbu4l { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 30px 0px 30px 0px; position: relative; width: 800px; }", ".framer-b855M .framer-1tmyzos { align-content: flex-start; align-items: flex-start; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 18px; height: auto; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }", ".framer-b855M .framer-a032bh, .framer-b855M .framer-1pxx5uj { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", ".framer-b855M .framer-1o4y26t { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: var(--framer-aspect-ratio-supported, 48px); justify-content: center; overflow: visible; padding: 0px; position: relative; width: 48px; }", ".framer-b855M .framer-qz0us0 { flex: none; height: 15px; position: relative; width: 15px; }", ...sharedStyle.css, '.framer-b855M[data-border="true"]::after, .framer-b855M [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 108
 * @framerIntrinsicWidth 800
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"csoo8gcZr":{"layout":["fixed","auto"]}}}
 * @framerVariables {"jIYTZ9Ber":"question","Jk4Ozxuso":"answer"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerjB2gDnqoz = withCSS(Component, css, "framer-b855M");
export default FramerjB2gDnqoz;
FramerjB2gDnqoz.displayName = "FAQ Accordion";
FramerjB2gDnqoz.defaultProps = {
    height: 108,
    width: 800
};
addPropertyControls(FramerjB2gDnqoz, {
    variant: {
        options: ["TRmLY9oqy", "csoo8gcZr"],
        optionTitles: ["Close", "Open"],
        title: "Variant",
        type: ControlType.Enum
    },
    jIYTZ9Ber: {
        defaultValue: "What’s the Portz progress like?",
        displayTextArea: false,
        title: "Question",
        type: ControlType.String
    },
    Jk4Ozxuso: {
        defaultValue: "I specialize in UX/UI design, web development, and branding for individuals and businesses.",
        description: "",
        displayTextArea: true,
        title: "Answer",
        type: ControlType.String
    }
});
addFonts(FramerjB2gDnqoz, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "../../../../../../../../framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "../../../../../../../../framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "../../../../../../../../framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "../../../../../../../../framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "../../../../../../../../framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "../../../../../../../../framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "../../../../../../../../framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerjB2gDnqoz",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "800",
                "framerColorSyntax": "true",
                "framerVariables": "{\"jIYTZ9Ber\":\"question\",\"Jk4Ozxuso\":\"answer\"}",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"csoo8gcZr\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicHeight": "108"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}