// Generated by Framer (9e04080)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Skills from "../../../../../../../../framerusercontent.com/modules/Tws3mqFDthCv7OMzgDb5/NjkYxuVkjfDs6vsYWNkh/OBiffso8d.js";
const SkillsFonts = getFonts(Skills);
const cycleOrder = ["qlgDmQVfs", "iol_sflcY", "xCDPCEpiC", "wXSklmIRC", "LEMVIChOG", "cAx2XqiYI", "WT_QUk2e_", "RerpckdY5", "mr23OrRkP", "QYwWzR9hP"];
const serializationHash = "framer-yJ9UA";
const variantClassNames = {
    cAx2XqiYI: "framer-v-gag8cy",
    iol_sflcY: "framer-v-29fg1m",
    LEMVIChOG: "framer-v-1q3cwzs",
    mr23OrRkP: "framer-v-11nn0rq",
    qlgDmQVfs: "framer-v-cr1xc5",
    QYwWzR9hP: "framer-v-z5fs7l",
    RerpckdY5: "framer-v-12gzyot",
    WT_QUk2e_: "framer-v-zmftwr",
    wXSklmIRC: "framer-v-84gb67",
    xCDPCEpiC: "framer-v-ubjf8g"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    delay: .1,
    duration: .3,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const transition2 = {
    delay: 0,
    duration: .4,
    ease: [.44, 0, .56, 1],
    type: "tween"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Figma mobile": "cAx2XqiYI",
    "Framer mobile": "RerpckdY5",
    "Premiere mobile": "mr23OrRkP",
    "PS mobile": "QYwWzR9hP",
    "Webflow mobile": "WT_QUk2e_",
    Figma: "qlgDmQVfs",
    Framer: "xCDPCEpiC",
    Premiere: "wXSklmIRC",
    PS: "LEMVIChOG",
    Webflow: "iol_sflcY"
};
const getProps = ({
    cursor,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        oIyvtfFH9: cursor ? ? props.oIyvtfFH9,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "qlgDmQVfs"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        oIyvtfFH9,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "qlgDmQVfs",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                ...addPropertyOverrides({
                    cAx2XqiYI: {
                        value: transition2
                    }
                }, baseVariant, gestureVariant),
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-cr1xc5", className, classNames),
                    "data-framer-cursor": oIyvtfFH9,
                    "data-framer-name": "Figma",
                    layoutDependency: layoutDependency,
                    layoutId: "qlgDmQVfs",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        cAx2XqiYI: {
                            "data-framer-cursor": undefined,
                            "data-framer-name": "Figma mobile"
                        },
                        iol_sflcY: {
                            "data-framer-name": "Webflow"
                        },
                        LEMVIChOG: {
                            "data-framer-name": "PS"
                        },
                        mr23OrRkP: {
                            "data-framer-cursor": undefined,
                            "data-framer-name": "Premiere mobile"
                        },
                        QYwWzR9hP: {
                            "data-framer-cursor": undefined,
                            "data-framer-name": "PS mobile"
                        },
                        RerpckdY5: {
                            "data-framer-cursor": undefined,
                            "data-framer-name": "Framer mobile"
                        },
                        WT_QUk2e_: {
                            "data-framer-cursor": undefined,
                            "data-framer-name": "Webflow mobile"
                        },
                        wXSklmIRC: {
                            "data-framer-name": "Premiere"
                        },
                        xCDPCEpiC: {
                            "data-framer-name": "Framer"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 64,
                        y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 64) - 0 - 64) / 2),
                        ...addPropertyOverrides({
                            cAx2XqiYI: {
                                y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 71) - 0 - 64) / 2)
                            },
                            mr23OrRkP: {
                                y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 71) - 0 - 64) / 2)
                            },
                            QYwWzR9hP: {
                                y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 71) - 0 - 64) / 2)
                            },
                            RerpckdY5: {
                                y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 71) - 0 - 64) / 2)
                            },
                            WT_QUk2e_: {
                                y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 71) - 0 - 64) / 2)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-79nzna-container",
                            layoutDependency: layoutDependency,
                            layoutId: "TRk8U0F1J-container",
                            nodeId: "TRk8U0F1J",
                            rendersWithMotion: true,
                            scopeId: "hMw2Bw8tW",
                            children: /*#__PURE__*/ _jsx(Skills, {
                                height: "100%",
                                id: "TRk8U0F1J",
                                JjQAn0DtX: "98%",
                                KoByj5e8W: "Figma",
                                layoutId: "TRk8U0F1J",
                                variant: "A9fPvEwta",
                                width: "100%",
                                ...addPropertyOverrides({
                                    cAx2XqiYI: {
                                        variant: "Ede3ilDW7"
                                    },
                                    iol_sflcY: {
                                        JjQAn0DtX: "86%",
                                        KoByj5e8W: "Webflow"
                                    },
                                    LEMVIChOG: {
                                        JjQAn0DtX: "75%",
                                        KoByj5e8W: "PS"
                                    },
                                    mr23OrRkP: {
                                        JjQAn0DtX: "80%",
                                        KoByj5e8W: "Premiere",
                                        variant: "Ede3ilDW7"
                                    },
                                    QYwWzR9hP: {
                                        JjQAn0DtX: "75%",
                                        KoByj5e8W: "PS",
                                        variant: "Ede3ilDW7"
                                    },
                                    RerpckdY5: {
                                        JjQAn0DtX: "90%",
                                        KoByj5e8W: "Framer",
                                        variant: "Ede3ilDW7"
                                    },
                                    WT_QUk2e_: {
                                        JjQAn0DtX: "86%",
                                        KoByj5e8W: "Webflow",
                                        variant: "Ede3ilDW7"
                                    },
                                    wXSklmIRC: {
                                        JjQAn0DtX: "80%",
                                        KoByj5e8W: "Premiere"
                                    },
                                    xCDPCEpiC: {
                                        JjQAn0DtX: "90%",
                                        KoByj5e8W: "Framer"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-yJ9UA.framer-l8p7u7, .framer-yJ9UA .framer-l8p7u7 { display: block; }", ".framer-yJ9UA.framer-cr1xc5 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-yJ9UA .framer-79nzna-container { flex: none; height: auto; position: relative; width: auto; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 64
 * @framerIntrinsicWidth 294.183
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"iol_sflcY":{"layout":["auto","auto"]},"xCDPCEpiC":{"layout":["auto","auto"]},"wXSklmIRC":{"layout":["auto","auto"]},"LEMVIChOG":{"layout":["auto","auto"]},"cAx2XqiYI":{"layout":["auto","auto"]},"WT_QUk2e_":{"layout":["auto","auto"]},"RerpckdY5":{"layout":["auto","auto"]},"mr23OrRkP":{"layout":["auto","auto"]},"QYwWzR9hP":{"layout":["auto","auto"]}}}
 * @framerVariables {"oIyvtfFH9":"cursor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerhMw2Bw8tW = withCSS(Component, css, "framer-yJ9UA");
export default FramerhMw2Bw8tW;
FramerhMw2Bw8tW.displayName = "Skills hover";
FramerhMw2Bw8tW.defaultProps = {
    height: 64,
    width: 294.183
};
addPropertyControls(FramerhMw2Bw8tW, {
    variant: {
        options: ["qlgDmQVfs", "iol_sflcY", "xCDPCEpiC", "wXSklmIRC", "LEMVIChOG", "cAx2XqiYI", "WT_QUk2e_", "RerpckdY5", "mr23OrRkP", "QYwWzR9hP"],
        optionTitles: ["Figma", "Webflow", "Framer", "Premiere", "PS", "Figma mobile", "Webflow mobile", "Framer mobile", "Premiere mobile", "PS mobile"],
        title: "Variant",
        type: ControlType.Enum
    },
    oIyvtfFH9: {
        title: "Cursor",
        type: ControlType.CustomCursor
    }
});
addFonts(FramerhMw2Bw8tW, [{
    explicitInter: true,
    fonts: []
}, ...SkillsFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerhMw2Bw8tW",
            "slots": [],
            "annotations": {
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"iol_sflcY\":{\"layout\":[\"auto\",\"auto\"]},\"xCDPCEpiC\":{\"layout\":[\"auto\",\"auto\"]},\"wXSklmIRC\":{\"layout\":[\"auto\",\"auto\"]},\"LEMVIChOG\":{\"layout\":[\"auto\",\"auto\"]},\"cAx2XqiYI\":{\"layout\":[\"auto\",\"auto\"]},\"WT_QUk2e_\":{\"layout\":[\"auto\",\"auto\"]},\"RerpckdY5\":{\"layout\":[\"auto\",\"auto\"]},\"mr23OrRkP\":{\"layout\":[\"auto\",\"auto\"]},\"QYwWzR9hP\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "294.183",
                "framerIntrinsicHeight": "64",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"oIyvtfFH9\":\"cursor\"}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}